Repository opencontainers/runc, pull requests merged in 2020-12, with the labels that each got.

#2679 libcontainer: isolate libcontainer/devices
  libcontainer/cgroups/devices/devices_emulator.go
  libcontainer/cgroups/devices/devices_emulator_test.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/devices_test.go
  libcontainer/cgroups/fs2/devices.go
  libcontainer/cgroups/systemd/common.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/configs/config.go
  libcontainer/configs/device_windows.go
  libcontainer/configs/devices.go
  libcontainer/devices/device.go
  libcontainer/devices/device_unix.go
  libcontainer/devices/device_windows.go
  libcontainer/devices/devices.go
  libcontainer/devices/devices_test.go
  libcontainer/integration/template_test.go
  libcontainer/rootfs_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
Labels: easy-to-review, kind/refactor

#2698 nsenter: hard-code memfd_create(2) syscall numbers
  libcontainer/nsenter/cloned_binary.c
Labels: area/nsenter

#2668 libcontainer/cgroups/fscommon: add openat2 support
  libcontainer/cgroups/fscommon/open.go
Labels: area/cgroupv1, area/cgroupv2

#2689 libct/cgroup/utils: fix GetCgroupMounts(all=true)
  libcontainer/cgroups/utils_test.go
  libcontainer/cgroups/v1_utils.go
Labels: area/cgroupv1, easy-to-review

#2709 remove "apparmor" and "selinux" build tags
  Makefile
  README.md
  go.mod
  go.sum
  libcontainer/apparmor/apparmor_linux.go
  libcontainer/apparmor/apparmor_unsupported.go
  script/release.sh
  vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go
  vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
  vendor/modules.txt
Labels: impact/changelog, kind/refactor
