Repository opencontainers/runc, pull requests merged in 2020-10, with the labels that each got.

#2618 CI: add golangci-lint via github actions
  .github/workflows/golangci-lint.yml
Labels: area/ci

#2608 libcontainer: remove redundant strings.Join()
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/nsenter/nsenter_test.go
Labels: easy-to-review, kind/refactor

#2623 libcontainer: remove the unused variable from spec
  libcontainer/specconv/spec_linux.go
Labels: easy-to-review, kind/refactor

#2621 libcontainer: remove loadConfig which is the unused function
  libcontainer/configs/config_linux_test.go
Labels: easy-to-review, kind/refactor

#2609 libcontainer: prefer bytes.TrimSpace() over strings.TrimSpace()
  libcontainer/cgroups/fs2/create.go
  libcontainer/cgroups/fs2/defaultpath_test.go
  libcontainer/cgroups/fscommon/utils.go
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/logs/logs_linux_test.go
  libcontainer/network_linux.go
Labels: easy-to-review, kind/refactor

#2597 Fix/improve GetHugePageSize
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
Labels: kind/performance, kind/refactor

#2528 cleancode: adjust and make it more readability
  libcontainer/factory_linux.go
Labels: easy-to-review, kind/refactor

#2605 libct/cgroups: switch to fscommon.{Read,Write}File
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/kmem.go
  libcontainer/cgroups/fs2/create.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fs2/pids.go
  libcontainer/cgroups/fscommon/fscommon_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/utils.go
Labels: area/cgroupv1, area/cgroupv2, easy-to-review

#2630 Rootless systemd dbus friendlier error
  docs/cgroup-v2.md
  libcontainer/cgroups/systemd/user.go
Labels: area/docs

#2648 Update bash completion to support new capabilities
  contrib/completions/bash/runc
Labels: easy-to-review

#2600 libcontainer/integration: fix cgroupv1 + systemd tests
  libcontainer/cgroups/systemd/v1.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/integration/seccomp_test.go
  libcontainer/integration/template_test.go
Labels: area/cgroupv1, area/ci

#2666 shfmt mounts.bats to pass `make validate`
  tests/integration/mounts.bats
Labels: area/ci, easy-to-review
