Repository opencontainers/runc, pull requests merged in 2020-08, with the labels that each got.

#2534 Pass location of CRIU binary to go-criu
  go.mod
  go.sum
  libcontainer/container_linux.go
  vendor/github.com/checkpoint-restore/go-criu/v4/.travis.yml
  vendor/github.com/checkpoint-restore/go-criu/v4/Makefile
  vendor/github.com/checkpoint-restore/go-criu/v4/go.sum
  vendor/github.com/checkpoint-restore/go-criu/v4/main.go
  vendor/modules.txt
Labels: area/checkpoint-restore

#2499 cgroupv1/FindCgroupMountpoint: add a fast path
  libcontainer/cgroups/v1_utils.go
Labels: area/cgroupv1, kind/performance

#2548 tests/int: fix error handling and logging
  tests/integration/checkpoint.bats
  tests/integration/hooks.bats
Labels: area/checkpoint-restore, area/ci

#2545 Makefile: fix go vet/fmt
  Makefile
Labels: area/ci, easy-to-review

#2553 support CAP_PERFMON, CAP_BPF, and CAP_CHECKPOINT_RESTORE
  go.mod
  go.sum
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/modules.txt
Labels: easy-to-review, enhancement

#2540 cgroups/fs tests: unify TestInvalid*Cgroup*
  libcontainer/cgroups/fs/fs_test.go
Labels: area/cgroupv1, area/ci, easy-to-review, kind/refactor

#2539 external pidns c/r code nits
  libcontainer/container_linux.go
Labels: easy-to-review, kind/refactor

#2547 libct/integration: enable some tests for cgroupv2
  libcontainer/integration/exec_test.go
Labels: area/cgroupv2, area/ci

#2549 Add shellcheck to bats files
  Makefile
  tests/integration/cgroups.bats
  tests/integration/checkpoint.bats
  tests/integration/create.bats
  tests/integration/delete.bats
  tests/integration/events.bats
  tests/integration/exec.bats
  tests/integration/hooks.bats
  tests/integration/kill.bats
  tests/integration/list.bats
  tests/integration/mask.bats
  tests/integration/mounts.bats
  tests/integration/pause.bats
  tests/integration/ps.bats
  tests/integration/root.bats
  tests/integration/spec.bats
  tests/integration/start.bats
  tests/integration/start_detached.bats
  tests/integration/state.bats
  tests/integration/tty.bats
  tests/integration/update.bats
Labels: area/ci

#2488 Modify spaces to tabs for indentation
  libcontainer/README.md
Labels: area/docs, easy-to-review

#2535 Fix run/exec with terminal: true in case stdin is not a terminal
  tests/integration/tty.bats
  tty.go
  utils_linux.go
Labels: area/terminal, bug
