Repository opencontainers/runc, pull requests merged in 2020-03, with the labels that each got.

#2228 Use "command -v" shell builtin instead of "which"
  man/md2man-all.sh
Labels: enhancement

#2238 Use named error return for initProcess#start
  libcontainer/process_linux.go
Labels: bug

#2252 Synchronize the call to linuxContainer.Signal()
  libcontainer/container_linux.go
Labels: bug

#1807 sd-notify: do not hang when NOTIFY_SOCKET is used with create
  notify_socket.go
  signals.go
  start.go
  utils_linux.go
Labels: bug

#2226 restore: fix a race condition in process.Wait()
  libcontainer/container_linux.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/restored_process.go
Labels: bug

#2248 cgroup2: fix conversion
  libcontainer/cgroups/fs2/cpu.go
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
  libcontainer/specconv/spec_linux.go
  update.go
Labels: bug

#1974 Remove unreachable code paths
  libcontainer/container_linux.go
  libcontainer/state_linux.go
Labels: easy-to-review

#1737 libcontainer/sync: Drop procConsole transaction from comments
  libcontainer/sync.go
Labels: easy-to-review, status/3-docs-review

#2264 Dockerfile: add -f to curl
  Dockerfile
Labels: easy-to-review

#1826 specconv: fix null spec.Process making runc panic
  libcontainer/specconv/spec_linux_test.go
Labels: bug, easy-to-review

#2267 Avoid duplicate calls to runner#destroy
  utils_linux.go
Labels: easy-to-review

#2263 Assorted minor nits in libcontainer
  libcontainer/cgroups/systemd/unified_hierarchy.go
  libcontainer/cgroups/utils.go
  libcontainer/intelrdt/intelrdt.go
Labels: easy-to-review

#2260 checkpoint: remove error message with --leave-running
  checkpoint.go
Labels: bug

#2193 fix readSync
  libcontainer/sync.go
Labels: bug, easy-to-review

#2270 cgroupv2: don't try to set kmem for systemd case
  libcontainer/cgroups/systemd/unified_hierarchy.go
Labels: easy-to-review

#2275 bifio.Scan.Err usage nits
  libcontainer/cgroups/fs2/defaultpath.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/user/user.go
Labels: easy-to-review

#2234 Dockerfile: some refactoring, and switch to "buster" variant
  Dockerfile
Labels: easy-to-review, enhancement

#2203 Separate systemd dbus connection initialization from running check
  libcontainer/cgroups/systemd/apply_nosystemd.go
  libcontainer/cgroups/systemd/apply_systemd.go
  libcontainer/cgroups/systemd/unified_hierarchy.go
  libcontainer/integration/exec_test.go
  utils_linux.go
Labels: enhancement
