Repository opencontainers/runc, pull requests merged in 2020-05, with the labels that each got.

#2375 Close fd in case fd.Write() returns error
  libcontainer/container_linux.go
Labels: easy-to-review

#2371 Use criu 3.14
  Dockerfile
  Vagrantfile
Labels: easy-to-review

#2370 let runc disable swap in cgroup v2
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/cgroups/utils.go
Labels: area/cgroupv2

#2352 fix runc events error in cgroup v2
  libcontainer/container_linux.go
  libcontainer/notify_linux_v2.go
  tests/integration/events.bats
Labels: area/cgroupv2

#2373 Logging nits
  checkpoint.go
  main.go
  utils.go
  utils_linux.go
Labels: easy-to-review

#2281 cgroup v2: support rootless systemd
  .travis.yml
  Vagrantfile
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/user.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/factory_linux.go
  rootless_linux.go
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
  tests/rootless.sh
  utils_linux.go
Labels: area/cgroupv2, area/rootless, area/systemd, enhancement

#2387 cgroup refactoring
  libcontainer/cgroups/fs/apply_raw.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/container_linux.go
  libcontainer/factory_linux.go
  libcontainer/notify_linux.go
  libcontainer/notify_linux_test.go
Labels: area/cgroupv2, kind/refactor

#2386 Simplify cgroup paths handling in v2 via unified v1/v2 API
  libcontainer/cgroups/cgroups.go
  libcontainer/cgroups/fs/apply_raw.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/systemd/unsupported.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
Labels: area/cgroupv2, kind/refactor

#2400 Dockerfile: bump bats to 1.2.0
  Dockerfile
Labels: area/ci

#2393 Vagrantfile: use criu from stable repo
  Vagrantfile
Labels: area/ci, easy-to-review

#2292 Add RDT Memory Bandwidth Monitoring (MBM) and Cache Monitoring Technology (CMT) statistics.
  events.go
  libcontainer/intelrdt/cmt.go
  libcontainer/intelrdt/cmt_test.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/mbm.go
  libcontainer/intelrdt/mbm_test.go
  libcontainer/intelrdt/monitoring.go
  libcontainer/intelrdt/monitoring_test.go
  libcontainer/intelrdt/stats.go
  types/events.go
Labels: enhancement

#2410 cgroupv2: never write empty string to memory.swap.max
  libcontainer/cgroups/fs2/memory.go
Labels: area/cgroupv2, bug

#2341 runc checkpoint: fix --status-fd to accept fd
  checkpoint.go
  libcontainer/container_linux.go
  libcontainer/criu_opts_linux.go
  restore.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, area/ci

#2401 libct/cgroup: rm GetClosestMountpointAncestor using moby/sys/mountinfo parser
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
Labels: kind/refactor

#2413 Add nil check of spec.Process in validateProcessSpec()
  checkpoint.go
  delete.go
  events.go
  libcontainer/cgroups/fs/apply_raw.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/stats_util_test.go
  libcontainer/cgroups/systemd/unsupported.go
  libcontainer/configs/validate/rootless.go
  libcontainer/configs/validate/validator.go
  libcontainer/container_linux.go
  libcontainer/init_linux.go
  libcontainer/keys/keyctl.go
  libcontainer/process_linux.go
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/sync.go
  list.go
  ps.go
  update.go
  utils_linux.go
Labels: bug

#2418 fix "libcontainer/cgroups/fs/cpuset.go:63:14: undefined: fmt"
  libcontainer/cgroups/fs/cpuset.go
Labels: bug, easy-to-review

#2409 Update to latest go-criu
  go.mod
  go.sum
  libcontainer/container_linux.go
  vendor/github.com/checkpoint-restore/go-criu/rpc/rpc.pb.go
  vendor/github.com/checkpoint-restore/go-criu/v4/.gitignore
  vendor/github.com/checkpoint-restore/go-criu/v4/.travis.yml
  vendor/github.com/checkpoint-restore/go-criu/v4/LICENSE
  vendor/github.com/checkpoint-restore/go-criu/v4/Makefile
  vendor/github.com/checkpoint-restore/go-criu/v4/README.md
  vendor/github.com/checkpoint-restore/go-criu/v4/go.mod
  vendor/github.com/checkpoint-restore/go-criu/v4/go.sum
  vendor/github.com/checkpoint-restore/go-criu/v4/main.go
  vendor/github.com/checkpoint-restore/go-criu/v4/notify.go
  vendor/github.com/checkpoint-restore/go-criu/v4/rpc/rpc.pb.go
  vendor/modules.txt
Labels: area/checkpoint-restore

#2333 Add CII Badge to README
  README.md
Labels: easy-to-review, status/3-docs-review

#2423 Fix setting some systemd limits, add more tests
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/cgroupv2, area/ci, area/systemd, bug

#2427 README.md: fix a dead link
  README.md
Labels: easy-to-review

#2422 Dockerfile: speed up criu build
  Dockerfile
Labels: easy-to-review, enhancement

#2426 Fix some cases of swap setting
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/cgroups/utils.go
  tests/integration/update.bats
Labels: area/cgroupv1, area/cgroupv2, bug

#2412 remove cgroup path recursively in cgroup v2
  libcontainer/cgroups/fs2/fs2.go
  tests/integration/delete.bats
Labels: area/cgroupv2, bug

#2437 cgroups/fs2: make removeCgroupPath faster
  libcontainer/cgroups/fs2/fs2.go
  tests/integration/delete.bats
Labels: area/cgroupv2, enhancement

#2420 Wait for criuProcess once
  libcontainer/container_linux.go
Labels: area/checkpoint-restore

#2441 cgroupv1: check cpu shares in place
  libcontainer/cgroups/fs/apply_raw.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/systemd/v1.go
Labels: area/cgroupv1, kind/refactor

#2416 cgroup2: exec: join the cgroup of the init process on EBUSY
  libcontainer/container_linux.go
  libcontainer/process_linux.go
  tests/integration/cgroups.bats
  tests/integration/delete.bats
  tests/integration/helpers.bash
Labels: area/cgroupv2

#2443 cgroupv1/systemd.Set: don't enable kernel memory acct
  libcontainer/cgroups/systemd/v1.go
Labels: area/cgroupv1

#2439 integration tests fixes for no swap ctrl case
  tests/integration/events.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/ci
