Repository opencontainers/runc, pull requests merged in 2020-04, with the labels that each got.

#2284 Avoid double close of criuServer
  libcontainer/container_linux.go
Labels: easy-to-review

#2283 isPathInPrefixList return value should be reverted
  libcontainer/container_linux.go
Labels: easy-to-review

#2261 vagrant: switch from VirtualBox to KVM + increase HW resources
  .travis.yml
  Vagrantfile
Labels: easy-to-review

#2235 Added HugeTlb controller for cgroupv2
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/hugetlb.go
Labels: enhancement

#2293 Restore close of criuServer
  libcontainer/container_linux.go
Labels: bug

#2289 Fix TestGetContainerStateAfterUpdate on cgroup v2
  libcontainer/container_linux_test.go
Labels: bug

#2297 libcontainer: use cgroups.NewStats
  libcontainer/cgroups/fs2/fs2.go
Labels: easy-to-review

#2296 README.md: update Go version to build
  README.md
Labels: easy-to-review

#2303 libcontainer: remove unneeded import
  libcontainer/cgroups/utils.go
Labels: easy-to-review

#2278 Exposing memory.numa_stats
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/fs/stats_util_test.go
  libcontainer/cgroups/stats.go
Labels: enhancement

#2317 Defer netns.Close() after error check
  libcontainer/container_linux.go
Labels: easy-to-review

#2299 cgroupv2: fix fs2 driver initialization
  .travis.yml
  libcontainer/cgroups/fs2/cpu.go
  libcontainer/cgroups/fs2/cpuset.go
  libcontainer/cgroups/fs2/create.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fs2/io.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/pids.go
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/unsupported.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/factory_linux.go
  tests/integration/checkpoint.bats
Labels: area/cgroupv2, bug

#2332 Fix/improve checkpoint integration tests
  tests/integration/checkpoint.bats
  tests/integration/helpers.bash
Labels: area/ci

#2348 libcontainer: use x/sys/unix instead of the hardcoded value
  libcontainer/system/linux.go
Labels: easy-to-review

#2330 libcontainer: use consts of Namespace from runtime-spec
  libcontainer/specconv/example.go
Labels: easy-to-review

#2336 Dockerfile: use bats-core
  Dockerfile
Labels: area/ci, enhancement

#2324 libcontainer: fix Checkpoint wrt cgroupv2
  libcontainer/container_linux.go
Labels: area/checkpoint-restore, bug, easy-to-review

#2334 Makefile nits
  Makefile
Labels: easy-to-review

#2347 cgroupv2: allow to set EnableAllDevices=true
  libcontainer/cgroups/fs2/devices.go
Labels: area/cgroupv2

#2335 Fix cgroupv2 checkpoint/restore
  Vagrantfile
  libcontainer/container_linux.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/rootfs_linux.go
  tests/integration/checkpoint.bats
Labels: area/cgroupv2, bug

#2327 checkpoint: don't print error if --pre-dump is set
  checkpoint.go
Labels: area/checkpoint-restore, easy-to-review

#2318 cgroupv2: use default allowed devices when linux resources is null
  libcontainer/specconv/spec_linux.go
Labels: area/cgroupv2, bug, easy-to-review

#2343 fix data inconsistent when runc update in systemd driven cgroup
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/systemd, enhancement

#2342 travis: run vagrant tests on the host
  .travis.yml
  Vagrantfile
Labels: area/ci

#2340 fs2: fix cgroup.subtree_control EPERM on rootless + add CI
  .travis.yml
  libcontainer/cgroups/fs2/create.go
  libcontainer/cgroups/fs2/fs2.go
  tests/integration/cgroups.bats
  tests/integration/update.bats
  tests/rootless.sh
Labels: area/cgroupv2, area/ci, area/rootless, bug

#2357 Makefile fixes and improvements
  Makefile
Labels: bug, kind/refactor

#2331 check that StartTransientUnit/StopUnit succeeds
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
Labels: area/systemd, bug

#2359 docs: terminals: mention subreaper requirement
  docs/terminals.md
Labels: area/docs

#2363 Vagrantfile: use Fedora 32 (and remove unused Podman)
  Vagrantfile
Labels: area/cgroupv2, area/checkpoint-restore, area/ci

#2358 cgroups/fs2: don't always parse /proc/self/cgroup
  libcontainer/cgroups/fs2/defaultpath.go
  libcontainer/cgroups/fs2/defaultpath_test.go
Labels: area/cgroupv2, kind/refactor
