Repository opencontainers/runc, pull requests merged in 2020-07, with the labels that each got.

#2496 libct/cgroups/fs: simplify/speedup freezer code
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/systemd/v1.go
Labels: area/cgroupv1, easy-to-review

#2503 cgroup, systemd: cleanup cgroups
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  tests/integration/delete.bats
Labels: area/cgroupv1, area/systemd, bug

#2505 fix redundant source code copy issue
  Dockerfile
Labels: area/ci, kind/refactor

#2501 fix TestPidsSystemd and TestRunWithKernelMemorySystemd test error
  .travis.yml
  libcontainer/integration/template_test.go
Labels: area/cgroupv1, area/ci, area/systemd

#2511 tests/fedora32: retry dnf
  Vagrantfile.centos7
  Vagrantfile.fedora32
Labels: area/ci

#2498 libct/cgroups/fs: code cleanups
  libcontainer/cgroups/fs/blkio.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/name.go
  libcontainer/cgroups/fs/net_cls.go
  libcontainer/cgroups/fs/net_prio.go
  libcontainer/cgroups/fs/perf_event.go
  libcontainer/cgroups/fs/pids.go
  libcontainer/cgroups/systemd/v1.go
Labels: area/cgroupv1, kind/refactor

#2510 tests/centos7: add criu
  Vagrantfile.centos7
  tests/integration/checkpoint.bats
  tests/integration/helpers.bash
Labels: area/ci

#2521 cleancode: clean code for utils_linux.go
  utils_linux.go
Labels: easy-to-review, kind/refactor

#2529 devices: correctly check device types
  libcontainer/devices/devices.go
  libcontainer/devices/devices_test.go
Labels: bug

#2500 libct/cgroups/fs: rework Apply()
  libcontainer/cgroups/fs/blkio.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpu_test.go
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/name.go
  libcontainer/cgroups/fs/net_cls.go
  libcontainer/cgroups/fs/net_prio.go
  libcontainer/cgroups/fs/perf_event.go
  libcontainer/cgroups/fs/pids.go
Labels: area/cgroupv1, kind/performance

#2507 libct/cgroups/GetCgroupRoot: make it faster
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/fs_test.go
Labels: area/cgroupv1, kind/performance
