Repository opencontainers/runc, pull requests merged in 2020-09, with the labels that each got.

#2580 tests/int: fix wrt busybox's nogroup->nobody change
  tests/integration/dev.bats
  tests/integration/exec.bats
Labels: area/ci

#2541 add Go version and libseccomp version to `runc --version`
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/seccomp/seccomp_unsupported.go
  main.go
Labels: easy-to-review, enhancement

#2494 cgroups/v1: optimize path usage
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/systemd/v1.go
Labels: area/cgroupv1, kind/performance

#2584 libct/cgroups: support Cgroups.Resources.Unified
  go.mod
  go.sum
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fscommon/fscommon.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/v1_utils.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/specconv/spec_linux.go
  tests/integration/cgroups.bats
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/modules.txt
Labels: area/cgroupv2

#2595 Libcontainer: refactor capabilities code and remove RHEL6 workaround
  libcontainer/capabilities_linux.go
Labels: impact/changelog

#2615 runc run: fix removing cgroups on error; improve logging on error
  libcontainer/container_linux.go
  libcontainer/process_linux.go
  tests/integration/cgroups.bats
Labels: area/cgroupv1, area/cgroupv2

#2614 libct/cgroups/systemd: eliminate runc/systemd race
  libcontainer/cgroups/systemd/common.go
Labels: area/systemd, bug

#2611 libcontainer/cgroups: use const for templates
  libcontainer/cgroups/fs/hugetlb_test.go
Labels: easy-to-review, kind/refactor

#2610 checkpoint: setPageServer: use net.SplitHostPort instead of strings.Split
  checkpoint.go
Labels: easy-to-review, kind/refactor

#2578 Makefile: fix DESTDIR handling
  Makefile
Labels: easy-to-review

#2604 libct/cgroups/fscommon: nits
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fscommon/fscommon.go
  libcontainer/cgroups/fscommon/utils.go
Labels: area/cgroupv1, area/cgroupv2, easy-to-review
