Repository opencontainers/runc, pull requests merged in 2020-06, with the labels that each got.

#2449 Fix #2440 omit cpuacct.usage_all when not available
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuacct_test.go
Labels: bug, easy-to-review

#2452 silence "which: no criu"
  tests/integration/helpers.bash
Labels: area/ci, easy-to-review

#2454 test "update rt period and runtime": fix up runtime and period
  tests/integration/update.bats
Labels: area/cgroupv1, area/ci, bug

#2455 add cgroup v2 documentation
  README.md
  docs/cgroup-v2.md
Labels: area/cgroupv2, area/docs, easy-to-review

#2414 use lazy-pages ready notification for criu >= 3.15
  libcontainer/container_linux.go
Labels: area/checkpoint-restore, enhancement

#2470 Fix #2469 omit memory.numa_stat when not available
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
Labels: area/cgroupv1, bug

#2338 fix path error in systemd when stopped
  libcontainer/cgroups/cgroups.go
  libcontainer/cgroups/fs/apply_raw.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/systemd/unsupported.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
  tests/integration/kill.bats
  tests/integration/ps.bats
Labels: area/cgroupv2, area/systemd, bug

#2453 CI: add CentOS 7 (kernel 3.10, systemd 219)
  .gitignore
  .travis.yml
  Vagrantfile.centos7
  Vagrantfile.fedora32
  libcontainer/integration/checkpoint_test.go
  script/install-vagrant.sh
  tests/integration/spec.bats
  tests/integration/update.bats
  tests/rootless.sh
Labels: area/ci, enhancement

#2411 libct/cgroups/utils: fix/separate cgroupv1 code
  libcontainer/cgroups/cgroups.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/fs_test.go
  libcontainer/cgroups/fs/unsupported.go
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
  libcontainer/cgroups/v1_utils.go
  libcontainer/container_linux.go
Labels: area/cgroupv2, area/checkpoint-restore, kind/refactor

#2466 cgroups/systemd: add setting CPUQuotaPeriod prop
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/systemd

#2478 libct/cgroups/readProcsFile: return an error if read failed
  libcontainer/cgroups/utils.go
Labels: bug, easy-to-review

#2229 Add CreateRuntime, CreateContainer and StartContainer Hooks
  Dockerfile
  Vagrantfile.centos7
  Vagrantfile.fedora32
  libcontainer/configs/config.go
  libcontainer/configs/config_linux_test.go
  libcontainer/configs/config_test.go
  libcontainer/container_linux.go
  libcontainer/factory_linux_test.go
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/process_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  libcontainer/standard_init_linux.go
  libcontainer/state_linux.go
  tests/integration/helpers.bash
  tests/integration/hooks.bats
  tests/integration/multi-arch.bash
Labels: enhancement

#2479 systemd: parse systemdVersion when only an int is returned
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
Labels: area/systemd, bug
