Repository opencontainers/runc, pull requests merged in 2020-11, with the labels that each got.

#2671 ci: pin shfmt to v3.2.0
  .travis.yml
Labels: area/ci, easy-to-review

#2658 tests/integration: rm excessive run use; fix exec --preserve-fds test
  tests/integration/checkpoint.bats
  tests/integration/create.bats
  tests/integration/debug.bats
  tests/integration/delete.bats
  tests/integration/events.bats
  tests/integration/exec.bats
  tests/integration/helpers.bash
  tests/integration/start_detached.bats
  tests/integration/start_hello.bats
Labels: area/ci

#2669 Initial v2 resources.unified systemd support
  go.mod
  go.sum
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/cpuset.go
  libcontainer/cgroups/systemd/cpuset_test.go
  libcontainer/cgroups/systemd/v2.go
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
  update.go
  vendor/github.com/willf/bitset/Makefile
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/go.mod
  vendor/github.com/willf/bitset/go.sum
  vendor/modules.txt
Labels: area/cgroupv2, area/systemd

#2583 restore: tell CRIU to use existing namespaces
  libcontainer/container_linux.go
Labels: area/checkpoint-restore

#2677 libcontainer/intelrdt: rename CAT and MBA enabled flags
  events.go
  libcontainer/configs/validate/validator.go
  libcontainer/container_linux_test.go
  libcontainer/factory_linux.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/intelrdt_test.go
  update.go
  utils_linux.go
Labels: easy-to-review, kind/refactor

#2676 docs: terminals: modify the example of Pass-Through mode.
  docs/terminals.md
Labels: area/docs

#2665 CI: update Fedora to 33
  .travis.yml
  Vagrantfile.fedora33
Labels: area/ci, easy-to-review

#2674 Move cgroup v2 out of experimental
  README.md
  docs/cgroup-v2.md
Labels: area/cgroupv2, impact/changelog

#2688 Dockerfile: bump criu to 3.15
  Dockerfile
Labels: area/ci, kind/dependency

#2681 integration: update README to link to bats-core
  tests/integration/README.md
Labels: area/docs, easy-to-review
