Repository opencontainers/runc, pull requests merged in 2021-12, with the labels that each got.

#3297 [1.0] Remove sub cgroup when container exits
  libcontainer/cgroups/systemd/v2.go
Labels: backport/1.0-pr

#3298 [1.0] script/release.sh: fix for opensuse
  script/release.sh
Labels: backport/1.0-pr

#3299 [1.0]: ci: add go 1.17, drop go 1.15
  .github/workflows/test.yml
Labels: backport/1.0-pr

#3057 chown cgroup to process uid in container namespace
  libcontainer/cgroups/systemd/v2.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/specconv/spec_linux.go
  tests/integration/cgroup_delegation.bats
Labels: enhancement, area/cgroupv2, area/systemd, impact/changelog

#3314 release: update libseccomp to 2.5.3, minor script fixes
  Dockerfile
  script/release_build.sh
  script/release_sign.sh
  script/seccomp.sh
Labels: kind/dependency

#3313 libct/int: minor improvements
  tests/integration/helpers.bash
  tests/integration/hooks.bats
Labels: area/ci

#3320 CHANGELOG: add an in-repo changelog file
  CHANGELOG.md
Labels: area/docs
