Repository opencontainers/runc, pull requests merged in 2021-08, with the labels that each got.

#3073 runc exec: fail with exit code of 255
  exec.go
  man/runc-exec.8.md
  tests/integration/exec.bats
  utils.go
Labels: area/ci, area/docs, impact/changelog

#3117 ci/cirrus: remove unused code
  .cirrus.yml
Labels: area/ci, easy-to-review

#3109 seccomp: skip redundant rules
  libcontainer/seccomp/config.go
  libcontainer/seccomp/seccomp_linux.go
  tests/integration/start_hello.bats
Labels: area/seccomp, backport/1.0-target, impact/changelog, kind/bug

#3115 [1.0] libct/cg/v1: work around CPU quota period set failure
  libcontainer/cgroups/fs/cpu.go
  tests/integration/update.bats
Labels: kind/bug, area/cgroupv1, backport/1.0-pr

#3129 [1.0] libct/seccomp: skip redundant rules
  libcontainer/seccomp/seccomp_linux.go
  tests/integration/start_hello.bats
Labels: kind/bug, area/seccomp, backport/1.0-pr

#3142 [1.0] script/release.sh: make builds reproducible
  Makefile
  script/release.sh
Labels: backport/1.0-pr

#3120 libct/nsenter: fix logging race in nsexec (regression in rc94)
  libcontainer/nsenter/nsexec.c
Labels: kind/bug, area/nsenter, area/logging, backport/1.0-target, regression

#3130 [1.0] fix logging race in nsexec (regression in rc94)
  libcontainer/nsenter/nsexec.c
Labels: kind/bug, area/nsenter, area/logging, regression, backport/1.0-pr

#3162 libct/nsenter: nullify pointer on asprintf error
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review

#3160 libct/nsenter: no need to check size_t less than 0
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review, area/nsenter

#3164 CI: Validate compilation without buildtags
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#3168 libct/nsenter: fix unused-result warning
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review, area/nsenter, backport/1.0-target

#3144 Fix codespell warnings, add codespell to ci
  .codespellrc
  .github/workflows/validate.yml
  docs/systemd.md
  libcontainer/cgroups/devices/devices_emulator.go
  libcontainer/cgroups/ebpf/ebpf_linux.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/stats_util_test.go
  libcontainer/cgroups/stats.go
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/container_linux.go
  libcontainer/nsenter/nsenter_test.go
  libcontainer/rootfs_linux.go
  libcontainer/standard_init_linux.go
  tests/integration/hooks.bats
  update.go
Labels: easy-to-review, area/ci

#3169 [1.0] libct/nsenter: fix unused-result warning
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review, area/nsenter, backport/1.0-pr

#3021 ci: add go1.17
  .github/workflows/test.yml
  Dockerfile
Labels: easy-to-review, area/ci, backport/1.0-target

#3116 ci/gha: add latest criu-dev test run
  .github/workflows/test.yml
Labels: easy-to-review, area/ci

#3166 libct/cg/sd/v1: fix freezeBeforeSet (alt 2)
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v1_test.go
  libcontainer/configs/cgroup_linux.go
Labels: kind/bug, area/systemd, area/cgroupv1, area/go-api, backport/1.0-target

#3167 [1.0] libct/cg/sd/v1: fix freezeBeforeSet (alt 2)
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v1_test.go
  libcontainer/configs/cgroup_linux.go
Labels: area/systemd, area/cgroupv1, area/go-api, backport/1.0-pr

#3159 libct/devices: change devices.Type to be a string
  libcontainer/cgroups/devices/devices_emulator.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/devices/device.go
  libcontainer/rootfs_linux.go
  libcontainer/specconv/spec_linux.go
Labels: kind/refactor

#3110 libct/cg/devices: stop using regex
  libcontainer/cgroups/devices/devices_emulator.go
  libcontainer/cgroups/devices/devices_emulator_test.go
Labels: kind/refactor, area/cgroupv1

#3136 libct/cg: rm dead code to improve clarity
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs2/defaultpath.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/configs/cgroup_linux.go
Labels: area/cgroupv2, kind/refactor, area/cgroupv1

#3090 libct/cg/v1: work around CPU quota period set failure
  .gitignore
  Makefile
  contrib/cmd/sd-helper/helper.go
  libcontainer/cgroups/fs/cpu.go
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: kind/bug, area/ci, area/systemd, area/cgroupv1, backport/1.0-target

#2920 libcontainer/intelrdt: support ClosID parameter
  libcontainer/configs/intelrdt.go
  libcontainer/configs/validate/validator.go
  libcontainer/container_linux.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/intelrdt_test.go
  libcontainer/intelrdt/util_test.go
  libcontainer/specconv/spec_linux.go
Labels: impact/changelog, area/intelrdt, kind/feature

#2883 Add support for rdma cgroup introduced in Linux Kernel 4.11
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/rdma.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fscommon/rdma.go
  libcontainer/cgroups/fscommon/rdma_test.go
  libcontainer/cgroups/stats.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/configs/rdma.go
  libcontainer/specconv/spec_linux.go
Labels: area/cgroupv2, area/cgroupv1, impact/changelog, kind/feature

#3190 Fix typo in bail message
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review

#2825 proposal: add --keep to runc run
  man/runc-run.8.md
  run.go
  tests/integration/run.bats
  utils_linux.go
Labels: impact/changelog, kind/feature
