Repository opencontainers/runc, pull requests merged in 2021-03, with the labels that each got.

#2809 Makefile cleanups
  .golangci.yml
  Makefile
  README.md
  script/validate-gofmt
Labels: area/ci, impact/changelog

#2842 tests/checkpoint: show full log lazy pages cpt
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, area/ci

#2798 Correctly restore containers with nested bind mounts
  libcontainer/container_linux.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore

#2852 libcontainer/apparmor: use sync.Once for AppArmor detection
  libcontainer/apparmor/apparmor_linux.go
Labels: area/apparmor, easy-to-review, kind/refactor

#2867 script/check-config.sh: add CONFIG_SECCOMP_FILTER
  script/check-config.sh
Labels: area/seccomp, easy-to-review

#2851 Fix build-tags in libcontainer/devices
  libcontainer/devices/device.go
  libcontainer/devices/device_unix.go
  libcontainer/devices/device_unix_test.go
  libcontainer/devices/device_windows.go
  libcontainer/devices/devices.go
Labels: easy-to-review, kind/refactor

#2820 fs2: fallback to setting io.weight if io.bfq.weight
  libcontainer/cgroups/fs2/io.go
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
  tests/integration/cgroups.bats
Labels: area/cgroupv2, impact/changelog

#2835 Fix init log forwarding race
  init.go
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
  libcontainer/factory_linux.go
  libcontainer/init_linux.go
  libcontainer/logs/logs.go
  libcontainer/logs/logs_linux_test.go
  libcontainer/process_linux.go
  libcontainer/restored_process.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  main.go
  tests/integration/debug.bats
  tests/integration/exec.bats
Labels: area/ci, area/logging

#2870 libct/seccomp: remove IsEnabled
  libcontainer/seccomp/fixtures/proc_self_status
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/seccomp/seccomp_linux_test.go
  libcontainer/seccomp/seccomp_unsupported.go
  main.go
Labels: easy-to-review

#2834 CI: cache ~/.vagrant.d/boxes
  .github/workflows/test.yml
Labels: area/ci, easy-to-review, enhancement

#2860 fix/simplify scripts/validate-c, fix *.c formatting
  .github/workflows/validate.yml
  Makefile
  libcontainer/nsenter/cloned_binary.c
  libcontainer/nsenter/nsexec.c
  script/.validate
  script/validate-c
Labels: area/ci, easy-to-review, kind/refactor

#2877 tests/int/cpt: better debug
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, area/ci, easy-to-review

#2874 script/check-config.sh: add SELinux and AppArmor
  script/check-config.sh
Labels: easy-to-review

#2802 libct: fix some container.Run fd leaks, add fd leak test
  libcontainer/container_linux.go
  libcontainer/integration/exec_test.go
Labels: bug
