Repository opencontainers/runc, pull requests merged in 2021-04, with the labels that each got.

#2871 Ensure the seccomp pipe is being read while exporting bpf
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
Labels: area/seccomp

#2854 capabilities: WARN, not ERROR, for unknown / unavailable capabilities
  go.mod
  go.sum
  libcontainer/capabilities/capabilities.go
  libcontainer/capabilities/capabilities_linux_test.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/modules.txt
Labels: enhancement, impact/changelog

#2890 tests: fix hello-world tarball name in testdata for arm64
  tests/integration/testdata/hello-world-arm64v8.tar
Labels: area/ci

#2885 libcontainer/configs: add missing type for hooknames
  libcontainer/configs/config.go
Labels: easy-to-review

#2881 tests/int: some refactoring, fix a flake
  libcontainer/container_linux.go
  tests/integration/cgroups.bats
  tests/integration/checkpoint.bats
  tests/integration/delete.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/ci

#2894 libct/init_linux: retry chdir to fix EPERM (regression in rc93)
  libcontainer/init_linux.go
  tests/integration/cwd.bats
Labels: impact/changelog

#2850 libcontainer/system: move userns utilities, remove `GetParentNSeuid`, `UIDMapInUserNS`
  checkpoint.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs2/devices.go
  libcontainer/cgroups/systemd/user.go
  libcontainer/cgroups/utils.go
  libcontainer/rootfs_linux.go
  libcontainer/system/linux.go
  libcontainer/system/unsupported.go
  libcontainer/system/userns_deprecated.go
  libcontainer/userns/userns.go
  libcontainer/userns/userns_fuzzer.go
  libcontainer/userns/userns_linux.go
  libcontainer/userns/userns_linux_test.go
  libcontainer/userns/userns_unsupported.go
  restore.go
  rootless_linux.go
Labels: easy-to-review, kind/refactor

#2844 More systemd cgroup driver documentation
  README.md
  docs/systemd-properties.md
  docs/systemd.md
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
Labels: area/docs, area/systemd

#2840 Ignore kernel memory settings
  README.md
  contrib/completions/bash/runc
  libcontainer/cgroups/fs/kmem.go
  libcontainer/cgroups/fs/kmem_disabled.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  man/runc-update.8.md
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
  update.go
Labels: area/cgroupv1, impact/changelog

#2912 Add cfs throttle stats to cgroup v2
  libcontainer/cgroups/fs2/cpu.go
Labels: area/cgroupv2, impact/changelog

#2873 libct/cg/fs2.GetStats() improvements
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/pids.go
Labels: area/cgroupv2, bug, impact/changelog, kind/refactor

#2818 Fix cgroup2 mount for rootless case
  libcontainer/container_linux.go
  libcontainer/init_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/specconv/example.go
  tests/integration/cgroups.bats
Labels: area/cgroupv2, area/rootless, bug, impact/changelog

#2911 logging: enable file/line info if --debug is set
  libcontainer/logs/logs.go
  main.go
Labels: area/logging

#2921 Fix fsmanager.GetStats performance (regression in rc93)
  libcontainer/cgroups/fs/fs_test.go
  libcontainer/cgroups/fscommon/open.go
  libcontainer/cgroups/fscommon/utils_test.go
Labels: area/cgroupv1, area/cgroupv2, kind/performance

#2906 libct/cg: make Set accept configs.Resources
  libcontainer/cgroups/cgroups.go
  libcontainer/cgroups/fs/blkio.go
  libcontainer/cgroups/fs/blkio_test.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpu_test.go
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/cpuset_test.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/devices_test.go
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/fs/freezer_test.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/hugetlb_test.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/fs/name.go
  libcontainer/cgroups/fs/net_cls.go
  libcontainer/cgroups/fs/net_cls_test.go
  libcontainer/cgroups/fs/net_prio.go
  libcontainer/cgroups/fs/net_prio_test.go
  libcontainer/cgroups/fs/perf_event.go
  libcontainer/cgroups/fs/pids.go
  libcontainer/cgroups/fs/pids_test.go
  libcontainer/cgroups/fs2/cpu.go
  libcontainer/cgroups/fs2/cpuset.go
  libcontainer/cgroups/fs2/create.go
  libcontainer/cgroups/fs2/devices.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fs2/io.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/pids.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
  libcontainer/process_linux.go
Labels: area/go-api, impact/changelog, kind/refactor

#2919 cloned_binary: switch from #error to #warning for SYS_memfd_create
  libcontainer/nsenter/cloned_binary.c
Labels: area/nsenter, easy-to-review
