Repository opencontainers/runc, pull requests merged in 2021-02, with the labels that each got.

#2787 ci/gha/fedora: retry vagrant up
  .github/workflows/test.yml
Labels: area/ci

#2741 ci: untangle getting test images
  .github/workflows/test.yml
  Dockerfile
  Makefile
  Vagrantfile.centos7
  Vagrantfile.fedora33
  libcontainer/integration/utils_test.go
  tests/integration/get-images.sh
  tests/integration/helpers.bash
  tests/integration/hooks.bats
  tests/integration/multi-arch.bash
  tests/integration/testdata/.gitignore
  tests/integration/testdata/hello-world-amd64.tar
  tests/integration/testdata/hello-world-arm64.tar
  tests/rootless.sh
Labels: area/ci

#2782 .golangci.yml: add
  .github/workflows/validate.yml
  .golangci.yml
Labels: area/ci, easy-to-review

#2793 cgroup2: devices: handle eBPF skipping more correctly
  libcontainer/cgroups/fs2/devices.go
Labels: area/cgroupv2

#2796 ebpf: fix device access check
  libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  tests/integration/dev.bats
  tests/integration/testdata/dev_access_test.c
Labels: area/cgroupv2, bug

#2803 apparmor: try attr/apparmor/exec before attr/exec
  libcontainer/apparmor/apparmor_linux.go
Labels: area/apparmor

#2806 README: add gha badges
  README.md
Labels: area/docs, easy-to-review

#2808 ci/gha: bump go 1.16-rc1 -> 1.16.x; fix gha ci
  .github/workflows/test.yml
Labels: area/ci, easy-to-review

#2816 Fix memory stats for cache in fs2
  libcontainer/cgroups/fs2/memory.go
Labels: area/cgroupv2, bug, impact/changelog

#2814 libct/cgroups/systemd: don't set limits in Apply
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
Labels: area/systemd

#2757 tests/int: cleanups
  tests/integration/README.md
  tests/integration/cgroups.bats
  tests/integration/checkpoint.bats
  tests/integration/create.bats
  tests/integration/cwd.bats
  tests/integration/debug.bats
  tests/integration/delete.bats
  tests/integration/dev.bats
  tests/integration/events.bats
  tests/integration/exec.bats
  tests/integration/helpers.bash
  tests/integration/hooks.bats
  tests/integration/kill.bats
  tests/integration/list.bats
  tests/integration/mask.bats
  tests/integration/mounts.bats
  tests/integration/no_pivot.bats
  tests/integration/pause.bats
  tests/integration/ps.bats
  tests/integration/root.bats
  tests/integration/seccomp.bats
  tests/integration/spec.bats
  tests/integration/start.bats
  tests/integration/start_detached.bats
  tests/integration/start_hello.bats
  tests/integration/state.bats
  tests/integration/tty.bats
  tests/integration/umask.bats
  tests/integration/update.bats
Labels: area/ci

#2799 Fix data races, enable testing with -race
  .github/workflows/test.yml
  Makefile
  libcontainer/configs/config.go
  libcontainer/integration/checkpoint_test.go
Labels: area/ci

#2812 Better handle hitting the memory limit
  libcontainer/cgroups/cgroups.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpu_test.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/fs2/cpu.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fscommon/utils.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
  libcontainer/notify_linux_v2.go
  libcontainer/process_linux.go
  tests/integration/cgroups.bats
  tests/integration/update.bats
Labels: enhancement, impact/changelog

#2768 ci/gha: add i386 unit test
  .github/workflows/test.yml
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
Labels: area/ci, easy-to-review
