Repository opencontainers/runc, pull requests merged in 2021-01, with the labels that each got.

#2712 libct/init_linux: reorder chdir to fix EPERM
  libcontainer/init_linux.go
  tests/integration/cwd.bats
  tests/rootless.sh
Labels: bug

#2711 libct/int/execin_tty: do help debug a flake
  libcontainer/integration/execin_test.go
Labels: area/ci, easy-to-review

#2706 libct/configs/validate.sysctl: fix host netns check
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
Labels: bug, impact/changelog

#2721 ci: replace travis with GHA for Fedora 33 and CentOS 7
  .github/workflows/test.yml
  .github/workflows/validate.yml
  .travis.yml
  Dockerfile
  script/tmpmount
  tests/integration/events.bats
Labels: area/ci

#2726 Remove script/install-vagrant.sh
  script/install-vagrant.sh
Labels: easy-to-review, kind/refactor

#2723 Fix a race in tty code leading to \r in output
  contrib/cmd/recvtty/recvtty.go
  libcontainer/init_linux.go
  libcontainer/integration/execin_test.go
  tty.go
  utils_linux.go
Labels: area/terminal

#2731 tests/int/multi-arch.bash: fix busybox URL
  tests/integration/multi-arch.bash
Labels: area/ci

#2714 README additions
  README.md
Labels: area/docs, easy-to-review

#2739 tests/int/hooks.bats: skip earlier
  tests/integration/hooks.bats
Labels: area/ci

#2740 README: rm travis badge
  README.md
Labels: easy-to-review

#2744 gha: don't check commits on push
  .github/workflows/validate.yml
Labels: area/ci

#2745 GHA: use ssh -tt instead of script tool (and fix CI failure reporting)
  .github/workflows/test.yml
  Makefile
  Vagrantfile.centos7
  script/validate-c
Labels: area/ci

#2727 libc/cg: convert r.CPU.Cpus/Mems to systemd props
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  tests/integration/update.bats
Labels: area/systemd

#2743 gha: cache docker layers to speed up make runcimage
  .github/workflows/validate.yml
Labels: area/ci

#2716 libct: suppress bogus "unable to terminate" warnings
  libcontainer/container_linux.go
Labels: enhancement

#2725 systemd: fix rootful-in-userns regression
  libcontainer/cgroups/systemd/user.go
  rootless_linux.go
Labels: area/systemd, bug

#2738 ci/unit tests: decrease verbosity
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/cgroups/systemd/cpuset_test.go
  libcontainer/cgroups/utils_test.go
Labels: area/ci, easy-to-review

#2771 Fix typo in README
  README.md
Labels: area/docs, easy-to-review

#2717 libct/checkProcMounts: optimize
  libcontainer/rootfs_linux.go
Labels: enhancement
