Repository opencontainers/runc, pull requests merged in 2021-11, with the labels that each got.

#3223 run create/run/exec: refuse bad cgroup
  contrib/completions/bash/runc
  exec.go
  libcontainer/factory_linux.go
  man/runc-exec.8.md
  tests/integration/cgroups.bats
Labels: area/cgroupv2, area/cgroupv1, impact/changelog

#3273 Vagrantfile.fedora: exclude systemd from upgrade
  .cirrus.yml
  Vagrantfile.fedora
Labels: area/ci

#3280 Revert "ci: temporarily disable criu repo gpg check"
  .github/workflows/test.yml
  Dockerfile
Labels: easy-to-review

#3270 libct: wrap more unix errors
  libcontainer/init_linux.go
  libcontainer/process_linux.go
  libcontainer/rootfs_linux.go
Labels: easy-to-review

#3282 [1.0] fix ci
  libcontainer/integration/checkpoint_test.go
  tests/integration/dev.bats
Labels: easy-to-review, area/ci

#3281 libct/specconv: reduce init allocations, use global maps, refactor
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
Labels: easy-to-review, kind/refactor

#3275 libcontainer/system: rm Prlimit
  libcontainer/init_linux.go
  libcontainer/system/linux.go
Labels: easy-to-review, kind/refactor

#3283 Fix failure with rw bind mount of a ro fuse
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  Vagrantfile.fedora
  libcontainer/rootfs_linux.go
  tests/integration/mounts_sshfs.bats
Labels: kind/bug, backport/1.0-target

#3284 Vagrantfile.fedora: revert excluding systemd
  Vagrantfile.fedora
Labels: area/ci

#3292 [1.0] Fix failure with rw bind mount of a ro fuse
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  Vagrantfile.fedora34
  libcontainer/rootfs_linux.go
  tests/integration/mounts_sshfs.bats
Labels: impact/changelog, backport/1.0-pr

#3294 libct/system/xattrs: remove
  libcontainer/system/xattrs_linux.go
Labels: easy-to-review, kind/refactor, impact/changelog

#3295 [1.0] libct/cg/fs2: fix GetStats for unsupported hugetlb
  libcontainer/cgroups/fs2/hugetlb.go
Labels: area/cgroupv2, backport/1.0-pr

#3277 [1.0] Fix failure with read-only /dev in spec
  libcontainer/rootfs_linux.go
  tests/integration/mounts.bats
Labels: impact/changelog, backport/1.0-pr

#3302 Enable unparam linter; fix/mute existing warnings
  .golangci.yml
  checkpoint.go
  libcontainer/cgroups/devices/devices_emulator.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
  libcontainer/cgroups/fs/blkio_test.go
  libcontainer/factory_linux.go
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/seccomp_test.go
  libcontainer/integration/utils_test.go
  notify_socket.go
  tty.go
  utils_linux.go
Labels: area/ci
