Repository opencontainers/runc, pull requests merged in 2021-05, with the labels that each got.

#2909 libct/int: misc cleanups and fixes
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/integration/seccomp_test.go
  libcontainer/integration/template_test.go
  libcontainer/integration/utils_test.go
Labels: area/ci

#2941 freezer: add delay after freeze
  libcontainer/cgroups/fs/freezer.go
Labels: area/cgroupv1, status/merge-on-green

#2937 libct/cg/sd: fix dbus connection leak (alternative)
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/dbus.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/integration/exec_test.go
Labels: area/systemd

#2913 tiny fix iterative checkpoint test case
  checkpoint.go
  restore.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, area/ci

#2950 EMERITUS: recognise previous maintainers
  EMERITUS.md
Labels: easy-to-review

#2932 CI: bump go 1.16, bats 1.3.0
  .github/workflows/test.yml
  Dockerfile
  Vagrantfile.centos7
Labels: area/ci, easy-to-review

#2945 ci/gha: bump shfmt and shellcheck
  .github/workflows/validate.yml
Labels: area/ci, easy-to-review

#2938 libcontainer/integration: nits
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/utils_test.go
Labels: area/ci, easy-to-review

#2940 libct/intelrdt: fix unit test
  libcontainer/intelrdt/intelrdt_test.go
Labels: area/ci, easy-to-review

#2951 cgroup2: devices filtering cleanup
  libcontainer/cgroups/devices/devices_emulator.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/cgroups/ebpf/ebpf.go
  libcontainer/cgroups/fs2/devices.go
  libcontainer/cgroups/systemd/common.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/specconv/spec_linux_test.go
  tests/integration/update.bats
Labels: area/cgroupv2, area/ebpf, impact/changelog

#2962 *: clean up remaining golangci-lint failures
  .github/workflows/validate.yml
  libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/integration/seccomp_test.go
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
  libcontainer/system/proc.go
Labels: area/ci, easy-to-review

#2956 Fix/improve runc -v
  Makefile
  main.go
Labels: easy-to-review

#2946 libct/cg/sd: return error from stopUnit
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
Labels: area/systemd

#2961 tests/int/dev: only call lsblk once
  tests/integration/dev.bats
Labels: area/ci
