Repository opencontainers/runc, pull requests merged in 2021-07, with the labels that each got.

#3033 libcontainer: rm own error system
  delete.go
  libcontainer/container.go
  libcontainer/container_linux.go
  libcontainer/error.go
  libcontainer/error_test.go
  libcontainer/factory.go
  libcontainer/factory_linux.go
  libcontainer/factory_linux_test.go
  libcontainer/generic_error.go
  libcontainer/generic_error_test.go
  libcontainer/process.go
  libcontainer/process_linux.go
  libcontainer/restored_process.go
  libcontainer/rootfs_linux.go
  libcontainer/setns_init_linux.go
  libcontainer/stacktrace/capture.go
  libcontainer/stacktrace/capture_test.go
  libcontainer/stacktrace/frame.go
  libcontainer/stacktrace/frame_test.go
  libcontainer/stacktrace/stacktrace.go
  libcontainer/standard_init_linux.go
  libcontainer/state_linux.go
  libcontainer/sync.go
  tests/integration/cgroups.bats
Labels: impact/changelog, kind/refactor

#3063 deps: update to github.com/cyphar/filepath-securejoin@v0.2.3
  go.mod
  go.sum
  vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/go.mod
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/cyphar/filepath-securejoin/vendor.conf
  vendor/modules.txt
Labels: dependencies, easy-to-review

#3045 retry unix.EINTR for container init process
  libcontainer/standard_init_linux.go
  libcontainer/system/linux.go
Labels: will-backport-to/1.0

#3058 libcontainer: Don't close already closed fds and bail on close(2) failures
  libcontainer/nsenter/nsexec.c
Labels: area/nsenter

#3074 [1.0] retry unix.EINTR for container init process
  libcontainer/standard_init_linux.go
  libcontainer/system/linux.go
Labels: impact/changelog

#3069 tests/int/dev: add CAP_SYSLOG to /dev/kmsg tests
  tests/integration/dev.bats
Labels: area/ci, easy-to-review

#3079 [1.0] libct/user: fix parsing long /etc/group lines
  libcontainer/user/user.go
  libcontainer/user/user_test.go
Labels: impact/changelog

#3041 libcontainer/intelrdt: cleanups
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/intelrdt_test.go
  libcontainer/intelrdt/stats.go
  libcontainer/specconv/spec_linux.go
Labels: area/intelrdt, kind/refactor

#3081 Make cgroup freezer only care about current control group (carry #3065)
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/systemd/systemd_test.go
Labels: will-backport-to/1.0

#3070 ci: enable unconvert linter, fix its warnings
  .golangci.yml
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fscommon/utils.go
  libcontainer/cgroups/utils.go
  libcontainer/container_linux.go
  libcontainer/devices/device_unix.go
  libcontainer/notify_linux_v2.go
Labels: area/ci, easy-to-review

#3055 cgroupv2: ebpf: ignore inaccessible existing programs
  go.mod
  go.sum
  libcontainer/cgroups/ebpf/ebpf_linux.go
  vendor/github.com/cilium/ebpf/asm/func.go
  vendor/github.com/cilium/ebpf/asm/func_string.go
  vendor/github.com/cilium/ebpf/elf_reader.go
  vendor/github.com/cilium/ebpf/internal/btf/btf.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types_string.go
  vendor/github.com/cilium/ebpf/internal/btf/types.go
  vendor/github.com/cilium/ebpf/internal/syscall.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/link/iter.go
  vendor/github.com/cilium/ebpf/link/syscalls.go
  vendor/github.com/cilium/ebpf/link/uprobe.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/syscalls.go
  vendor/github.com/cilium/ebpf/types.go
  vendor/github.com/cilium/ebpf/types_string.go
  vendor/modules.txt
Labels: area/cgroupv2, area/ebpf, bug, regression, will-backport-to/1.0

#3085 [1.0] Make cgroup freezer only care about current control group
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/systemd/systemd_test.go
Labels: area/cgroupv1, impact/changelog

#3087 [1.0] cgroupv2: ebpf: ignore inaccessible existing programs
  go.mod
  go.sum
  libcontainer/cgroups/ebpf/ebpf_linux.go
  vendor/github.com/cilium/ebpf/asm/func.go
  vendor/github.com/cilium/ebpf/asm/func_string.go
  vendor/github.com/cilium/ebpf/elf_reader.go
  vendor/github.com/cilium/ebpf/internal/btf/btf.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types_string.go
  vendor/github.com/cilium/ebpf/internal/btf/types.go
  vendor/github.com/cilium/ebpf/internal/syscall.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/link/iter.go
  vendor/github.com/cilium/ebpf/link/syscalls.go
  vendor/github.com/cilium/ebpf/link/uprobe.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/syscalls.go
  vendor/github.com/cilium/ebpf/types.go
  vendor/github.com/cilium/ebpf/types_string.go
  vendor/modules.txt
Labels: area/cgroupv2, area/ebpf, impact/changelog

#3092 [1.0] Don't freeze cgroup on update for systemd cgroup v2
  libcontainer/cgroups/systemd/v2.go
  tests/integration/update.bats
Labels: area/cgroupv2, area/ci, area/systemd, backport/1.0-pr, impact/changelog

#3082 cgroups: Set: fix freeze, avoid unnecessary freeze from systemd v1
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/template_test.go
  libcontainer/integration/utils_test.go
Labels: area/cgroupv1, area/ci, backport/1.0-target

#3093 [1.0] cgroups: Set: fix freeze, avoid unnecessary freeze from systemd v1
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/template_test.go
  libcontainer/integration/utils_test.go
Labels: area/cgroupv1, area/ci, area/systemd, backport/1.0-pr, impact/changelog

#3095 [1.0] VERSION: release 1.0.1
  VERSION
Labels: backport/1.0-pr

#3088 Use Cirrus CI for Vagrant tests
  .cirrus.yml
  .github/workflows/test.yml
Labels: area/ci, backport/1.0-target

#3103 README.md: remove abandoned versioning policy
  README.md
Labels: area/docs

#3104 Do not use Vagrant for CentOS 7/8
  .cirrus.yml
  Vagrantfile.centos7
  tests/integration/update.bats
  tests/rootless.sh
Labels: area/ci, backport/1.0-target

#3100 Drop Go 1.13 support, require go 1.15+
  .github/workflows/test.yml
  Makefile
  README.md
  go.mod
  libcontainer/cgroups/fs/blkio_test.go
  libcontainer/cgroups/fs/cpu_test.go
  libcontainer/cgroups/fs/cpuacct_test.go
  libcontainer/cgroups/fs/cpuset_test.go
  libcontainer/cgroups/fs/devices_test.go
  libcontainer/cgroups/fs/freezer_test.go
  libcontainer/cgroups/fs/hugetlb_test.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/fs/net_cls_test.go
  libcontainer/cgroups/fs/net_prio_test.go
  libcontainer/cgroups/fs/pids_test.go
  libcontainer/cgroups/fs/util_test.go
  libcontainer/cgroups/fs2/io_test.go
  libcontainer/cgroups/fscommon/utils.go
  libcontainer/cgroups/fscommon/utils_test.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/container_linux_test.go
  libcontainer/factory_linux_test.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/integration/init_test.go
  libcontainer/integration/seccomp_test.go
  libcontainer/integration/template_test.go
  libcontainer/integration/update_test.go
  libcontainer/integration/utils_test.go
  libcontainer/intelrdt/cmt_test.go
  libcontainer/intelrdt/intelrdt_test.go
  libcontainer/intelrdt/mbm_test.go
  libcontainer/intelrdt/monitoring_test.go
  libcontainer/intelrdt/util_test.go
  libcontainer/logs/logs_linux_test.go
  libcontainer/notify_linux_test.go
  vendor/modules.txt
Labels: impact/changelog, status/merge-on-green

#3113 runc init: remove some code
  init.go
  libcontainer/nsenter/nsexec.c
  libcontainer/process_linux.go
  main.go
Labels: kind/refactor
