Repository opencontainers/runc, pull requests merged in 2021-06, with the labels that each got.

#2968 cgroup2: map io.stats to v1 blkio.stats correctly
  libcontainer/cgroups/fs2/io.go
  libcontainer/cgroups/fs2/io_test.go
Labels: area/cgroupv2, impact/changelog

#2985 docs/terminals.md: add troubleshooting
  docs/terminals.md
Labels: area/docs, area/terminal, easy-to-review

#2997 [rc94 regression] libct/cg/sd: fix dbus error handling
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
Labels: area/systemd, impact/changelog

#2999 libcontainer: remove aliases for deprecated functions
  libcontainer/configs/devices.go
  libcontainer/system/userns_deprecated.go
Labels: impact/changelog, kind/refactor

#2994 runc update: skip devices
  libcontainer/configs/cgroup_linux.go
  update.go
Labels: area/cgroupv1, area/cgroupv2, impact/changelog

#2986 cgroupv2: ebpf: check for BPF_F_REPLACE support and degrade gracefully
  libcontainer/cgroups/ebpf/ebpf_linux.go
Labels: area/cgroupv2, bug

#3010 libcontainer/cgroups/fs/blkio: support BFQ weight[_device]
  libcontainer/cgroups/fs/blkio.go
  libcontainer/cgroups/fs/blkio_test.go
Labels: area/cgroupv1, bug

#3009 update cilium/ebpf to fix haveBpfProgReplace() check
  go.mod
  go.sum
  libcontainer/cgroups/ebpf/ebpf_linux.go
  vendor/github.com/cilium/ebpf/CONTRIBUTING.md
  vendor/github.com/cilium/ebpf/link/kprobe.go
  vendor/github.com/cilium/ebpf/link/platform.go
  vendor/github.com/cilium/ebpf/link/program.go
  vendor/modules.txt
Labels: area/cgroupv2, area/ebpf, easy-to-review

#3005 Allow restoring with a different LSM profile
  libcontainer/container_linux.go
  libcontainer/criu_opts_linux.go
  man/runc-restore.8.md
  restore.go
Labels: area/checkpoint-restore, impact/changelog

#3024 libct/cg: mv fscommon.{Open,Read,Write}File to cgroups
  libcontainer/cgroups/file.go
  libcontainer/cgroups/file_test.go
  libcontainer/cgroups/fs/blkio.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/fs/fs_test.go
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/net_cls.go
  libcontainer/cgroups/fs/net_prio.go
  libcontainer/cgroups/fs/pids.go
  libcontainer/cgroups/fs/util_test.go
  libcontainer/cgroups/fs2/cpu.go
  libcontainer/cgroups/fs2/cpuset.go
  libcontainer/cgroups/fs2/create.go
  libcontainer/cgroups/fs2/freezer.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/hugetlb.go
  libcontainer/cgroups/fs2/io.go
  libcontainer/cgroups/fs2/io_test.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/pids.go
  libcontainer/cgroups/fscommon/fscommon.go
  libcontainer/cgroups/fscommon/utils.go
  libcontainer/cgroups/fscommon/utils_test.go
  libcontainer/cgroups/utils.go
Labels: kind/refactor

#3029 checkpoint: set default work-dir to image-path
  libcontainer/container_linux.go
Labels: area/checkpoint-restore, impact/changelog

#2902 checkpoint: resolve symlink for external bind mount
  libcontainer/container_linux.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore

#3051 tests/int/no_pivot: fixup for new kernels
  tests/integration/no_pivot.bats
Labels: area/ci

#3053 libct/rootfs: consolidate utils imports
  libcontainer/rootfs_linux.go
Labels: easy-to-review, kind/refactor
