Repository opencontainers/runc, pull requests merged in 2021-09, with the labels that each got.

#3030 libct/cg/OpenFile: fix/improve openat2 handling
  libcontainer/cgroups/file.go
  libcontainer/cgroups/file_test.go
Labels: kind/bug, area/cgroupv2, area/cgroupv1

#3158 libct/nsenter/nsenter_test.go: fix and improve
  libcontainer/nsenter/nsenter_test.go
Labels: area/ci, area/logging

#3198 optimize log: move WriteJSON defer as early as possible
  libcontainer/factory_linux.go
Labels: easy-to-review

#3200 script/release.sh: fix for opensuse
  script/release.sh
Labels: backport/1.0-target

#2682 Implement seccomp notify support
  .gitignore
  Makefile
  contrib/cmd/seccompagent/README.md
  contrib/cmd/seccompagent/config.json
  contrib/cmd/seccompagent/seccompagent.go
  contrib/cmd/seccompagent/unsupported.go
  go.mod
  go.sum
  libcontainer/configs/config.go
  libcontainer/factory_linux.go
  libcontainer/init_linux.go
  libcontainer/process_linux.go
  libcontainer/seccomp/config.go
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/seccomp/seccomp_unsupported.go
  libcontainer/setns_init_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  libcontainer/standard_init_linux.go
  libcontainer/sync.go
  libcontainer/utils/cmsg.go
  tests/integration/helpers.bash
  tests/integration/seccomp-notify-compat.bats
  tests/integration/seccomp-notify.bats
  tests/integration/seccomp.bats
  vendor/github.com/seccomp/libseccomp-golang/.travis.yml
  vendor/github.com/seccomp/libseccomp-golang/CONTRIBUTING.md
  vendor/github.com/seccomp/libseccomp-golang/Makefile
  vendor/github.com/seccomp/libseccomp-golang/README.md
  vendor/github.com/seccomp/libseccomp-golang/go.mod
  vendor/github.com/seccomp/libseccomp-golang/go.sum
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
  vendor/modules.txt
Labels: impact/changelog, area/seccomp, kind/feature

#3047 checkpoint: resolve symlink for external bind mount (take II)
  libcontainer/container_linux.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, impact/changelog

#2696 libct/system.Stat: fix panic, speed up, add benchmarks
  libcontainer/system/proc.go
  libcontainer/system/proc_test.go
Labels: kind/bug, kind/refactor, kind/performance

#3157 Logging improvements
  init.go
  libcontainer/logs/logs.go
  libcontainer/logs/logs_linux_test.go
  main.go
Labels: kind/refactor, area/logging

#3186 rootless+cgroup2+systemd: improve error message when dbus-user-session is not installed
  libcontainer/cgroups/systemd/dbus.go
Labels: easy-to-review, area/cgroupv2, area/rootless, area/systemd, backport/1.0-target

#3204 Add support for seccomp actions ActKillThread and ActKillProcess
  libcontainer/configs/config.go
  libcontainer/seccomp/seccomp_linux.go
Labels: easy-to-review, area/seccomp

#3208 ci/gha: update golangci-lint to 1.42.1
  .github/workflows/validate.yml
  contrib/cmd/seccompagent/seccompagent.go
  contrib/cmd/seccompagent/unsupported.go
Labels: easy-to-review, area/ci

#3207 ci/gha: bump shfmt to 3.3.1
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#3201 nsexec.c: don't write logs that are to be discarded
  exec.go
  init.go
  libcontainer/nsenter/nsexec.c
  utils_linux.go
Labels: area/nsenter, area/logging

#3214 runc cli: nits
  create.go
  delete.go
  restore.go
  run.go
  start.go
  utils_linux.go
Labels: easy-to-review, kind/refactor

#3212 [1.0] rootless+cgroup2+systemd: improve error message when dbus-user-session is not installed #3186
  libcontainer/cgroups/systemd/dbus.go
Labels: area/cgroupv2, area/rootless, area/systemd, backport/1.0-pr

#3217 runc delete -f: fix for cg v1 + paused container
  libcontainer/container_linux.go
  tests/integration/delete.bats
Labels: area/cgroupv1, impact/changelog

#3215 cgroupv1: refactor and optimize
  libcontainer/cgroups/fs/blkio.go
  libcontainer/cgroups/fs/blkio_test.go
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpu_test.go
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuacct_test.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs/cpuset_test.go
  libcontainer/cgroups/fs/devices.go
  libcontainer/cgroups/fs/devices_test.go
  libcontainer/cgroups/fs/freezer.go
  libcontainer/cgroups/fs/freezer_test.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/fs_test.go
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/hugetlb_test.go
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/fs/name.go
  libcontainer/cgroups/fs/net_cls.go
  libcontainer/cgroups/fs/net_cls_test.go
  libcontainer/cgroups/fs/net_prio.go
  libcontainer/cgroups/fs/net_prio_test.go
  libcontainer/cgroups/fs/paths.go
  libcontainer/cgroups/fs/paths_test.go
  libcontainer/cgroups/fs/perf_event.go
  libcontainer/cgroups/fs/pids.go
  libcontainer/cgroups/fs/pids_test.go
  libcontainer/cgroups/fs/rdma.go
  libcontainer/cgroups/fs/util_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
Labels: kind/refactor, area/cgroupv1

#3216 cgroup: make paths available, simplify getting manager
  contrib/cmd/sd-helper/helper.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs/fs_test.go
  libcontainer/cgroups/fs/paths.go
  libcontainer/cgroups/fs2/defaultpath.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/manager/manager_test.go
  libcontainer/cgroups/manager/new.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v1_test.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/factory_linux.go
  libcontainer/factory_linux_test.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/template_test.go
  libcontainer/integration/utils_test.go
  libcontainer/specconv/spec_linux.go
  utils_linux.go
Labels: area/cgroupv2, area/cgroupv1, area/go-api, impact/changelog
