Repository opencontainers/runc, pull requests merged in 2022-03, with the labels that each got.

#3381 ensure the path is a sub-cgroup path
  libcontainer/container_linux.go
  tests/integration/exec.bats
Labels: area/cgroupv2, area/cgroupv1, backport/todo/1.1

#3382 configs/validate: looser validation for RDT
  libcontainer/configs/validate/validator.go
Labels: easy-to-review, area/intelrdt, backport/todo/1.1

#3370 ci: bump golangci-lint to v1.44, golangci-lint-action to v3
  .github/workflows/validate.yml
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/process_linux.go
  update.go
Labels: easy-to-review

#3403 [1.1] runc exec --cgroup: ensure the path is a sub-cgroup path
  libcontainer/container_linux.go
  tests/integration/exec.bats
Labels: area/cgroupv2, area/cgroupv1, backport/1.1-pr

#3374 Assorted CLI nitpicks
  checkpoint.go
  list.go
  main.go
  restore.go
  rootless_linux.go
  utils.go
  utils_linux.go
Labels: kind/refactor, impact/changelog

#3356 libct/cg/sd: simplify DetectUserDbusSessionBusAddress
  libcontainer/cgroups/systemd/user.go
Labels: area/cgroupv2, area/rootless

#3404 [1.1] libct/cg/sd/v2: fix ENOENT on cgroup delegation
  libcontainer/cgroups/systemd/v2.go
Labels: area/cgroupv2, area/systemd, backport/1.1-pr

#3406 [release-1.1] configs/validate: looser validation for RDT
  libcontainer/configs/validate/validator.go
Labels: area/intelrdt, backport/1.1-pr

#3416 tests: Improve seccomp-notify test names and description
  tests/integration/seccomp-notify.bats
Labels: easy-to-review, area/ci

#3392 tests/int: runc delete: fix flake, enable for rootless
  tests/integration/delete.bats
Labels: area/ci

#3367 tests: add `set -u`
  tests/integration/cgroups.bats
  tests/integration/checkpoint.bats
  tests/integration/cwd.bats
  tests/integration/help.bats
  tests/integration/helpers.bash
  tests/integration/hooks.bats
  tests/integration/list.bats
  tests/integration/root.bats
  tests/integration/update.bats
  tests/rootless.sh
Labels: area/ci

#3424 README,libct/README: fix pkg.go.dev badges
  README.md
  libcontainer/README.md
Labels: easy-to-review, backport/todo/1.1

#3419 Add / switch to Go 1.18
  .cirrus.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Dockerfile
  README.md
  Vagrantfile.fedora
  go.mod
  libcontainer/container_linux.go
  libcontainer/devices/device_unix_go116_test.go
  libcontainer/devices/device_unix_go117_test.go
  libcontainer/devices/device_unix_test.go
  vendor/github.com/checkpoint-restore/go-criu/v5/go.mod
  vendor/github.com/checkpoint-restore/go-criu/v5/go.sum
  vendor/github.com/cilium/ebpf/go.mod
  vendor/github.com/cilium/ebpf/go.sum
  vendor/github.com/containerd/console/go.mod
  vendor/github.com/containerd/console/go.sum
  vendor/github.com/cyphar/filepath-securejoin/go.mod
  vendor/github.com/godbus/dbus/v5/go.mod
  vendor/github.com/godbus/dbus/v5/go.sum
  vendor/github.com/moby/sys/mountinfo/go.mod
  vendor/github.com/moby/sys/mountinfo/go.sum
  vendor/github.com/mrunalp/fileutils/go.mod
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/seccomp/libseccomp-golang/go.mod
  vendor/github.com/seccomp/libseccomp-golang/go.sum
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/urfave/cli/go.mod
  vendor/github.com/urfave/cli/go.sum
  vendor/github.com/vishvananda/netlink/go.mod
  vendor/github.com/vishvananda/netlink/go.sum
  vendor/github.com/vishvananda/netns/go.mod
  vendor/github.com/vishvananda/netns/go.sum
  vendor/modules.txt
Labels: area/ci

#3373 Remove Factory and LinuxFactory
  init.go
  libcontainer/README.md
  libcontainer/cgroups/manager/new.go
  libcontainer/factory.go
  libcontainer/factory_linux.go
  libcontainer/factory_linux_test.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/init_test.go
  libcontainer/integration/utils_test.go
  libcontainer/restored_process.go
  list.go
  utils_linux.go
Labels: kind/refactor

#3427 CI/cirrus: add centos-stream-9
  .cirrus.yml
Labels: area/ci, backport/todo/1.1

#3375 libct: rm BaseContainer and Container interfaces
  delete.go
  libcontainer/container.go
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
  libcontainer/factory_linux.go
  libcontainer/factory_linux_test.go
  libcontainer/integration/utils_test.go
  libcontainer/process_linux.go
  libcontainer/state_linux.go
  libcontainer/state_linux_test.go
  notify_socket.go
  utils_linux.go
Labels: easy-to-review, kind/refactor

#3433 libct/cg: IsCgroup2HybridMode: don't panic
  libcontainer/cgroups/utils.go
Labels: area/cgroupv1, backport/todo/1.1

#3436 [1.1] add centos-stream-9
  .cirrus.yml
Labels: area/ci, backport/1.1-pr

#3443 ci/gha: run on main branch
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci
