Repository opencontainers/runc, pull requests merged in 2022-11, with the labels that each got.

#3405 libct/seccomp: enable seccomp binary tree optimization
  libcontainer/seccomp/seccomp_linux.go
Labels: kind/performance, impact/changelog, area/seccomp

#3640 [1.1] ci: shellcheck: update to 0.8.0, fix/suppress new warnings
  .github/workflows/validate.yml
  tests/integration/events.bats
  tests/integration/helpers.bash
Labels: area/ci, backport/1.1-pr

#3631 Fix comment of signalAllProcesses for process wait due to sigkill
  libcontainer/init_linux.go
Labels: easy-to-review

#3379 ci: bump shfmt to 3.5.1, simplify CI setup
  .editorconfig
  .github/workflows/validate.yml
  Makefile
Labels: easy-to-review, area/ci

#3579 runc update: implement memory.checkBeforeUpdate
  go.mod
  go.sum
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/specconv/spec_linux.go
  tests/integration/update.bats
  update.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/modules.txt
Labels: area/cgroupv2

#3654 go.mod: golang.org/x/*: use tagged versions
  go.mod
  go.sum
  vendor/golang.org/x/net/AUTHORS
  vendor/golang.org/x/net/CONTRIBUTORS
  vendor/golang.org/x/net/bpf/doc.go
  vendor/golang.org/x/net/bpf/vm_instructions.go
  vendor/golang.org/x/sys/unix/asm_bsd_ppc64.s
  vendor/golang.org/x/sys/unix/dirent.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_illumos.go
  vendor/golang.org/x/sys/unix/syscall_openbsd_libc.go
  vendor/golang.org/x/sys/unix/syscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/syscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix_gc.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_illumos_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysctl_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsysctl_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_illumos_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_solaris_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: easy-to-review

#3662 Fixed Init State Error Variable
  libcontainer/process_linux.go
Labels: easy-to-review

#3655 runc checkpoint: destroy only on success
  checkpoint.go
Labels: area/checkpoint-restore

#3670 Vagrantfile.fedora: upgrade Fedora to 37
  Vagrantfile.fedora
Labels: easy-to-review, area/ci
