Repository opencontainers/runc, pull requests merged in 2022-06, with the labels that each got.

#3489 libcontainer: relax getenv_int sanity check
  libcontainer/nsenter/nsexec.c
Labels: backport/done/1.0

#3494 [1.1] libcontainer: relax getenv_int sanity check
  libcontainer/nsenter/nsexec.c
Labels: backport/1.1-pr

#3498 cgroups: systemd: skip adding device paths that don't exist
  libcontainer/cgroups/devices/systemd.go
Labels: easy-to-review, area/systemd, area/cgroupv1, backport/done/1.1

#3504 [1.1] cgroups: systemd: skip adding device paths that don't exist
  libcontainer/cgroups/systemd/common.go
Labels: easy-to-review, area/systemd, backport/1.1-pr

#3510 libct: fix mounting via wrong proc fd
  libcontainer/rootfs_linux.go
  tests/integration/userns.bats
Labels: kind/bug, regression, backport/done/1.1

#3515 Bump golangci-lint, fix an error path
  .github/workflows/validate.yml
  libcontainer/factory_linux.go
Labels: easy-to-review, area/ci
