Repository opencontainers/runc, pull requests merged in 2022-10, with the labels that each got.

#3628 cirrus-ci: install EPEL on CentOS 7 conditionally
  .cirrus.yml
Labels: easy-to-review, area/ci, backport/todo/1.1

#3603 tests/int: do not set inheritable capabilities
  tests/integration/dev.bats
  tests/integration/update.bats
Labels: easy-to-review, area/ci

#3630 [1.1] cirrus-ci: install EPEL on CentOS 7 conditionally
  .cirrus.yml
Labels: easy-to-review, area/ci, backport/1.1-pr

#3626 libcontainer/cgroups: return concrete types
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/systemd/devices.go
  libcontainer/cgroups/systemd/freeze_test.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
Labels: easy-to-review, kind/refactor

#3611 cgroups: cpuset: fix byte order while parsing cpuset range to bits
  libcontainer/cgroups/systemd/cpuset.go
  libcontainer/cgroups/systemd/cpuset_test.go
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: kind/bug, backport/todo/1.1

#3650 tests/int/seccomp: fix flags test on ARM
  tests/integration/seccomp.bats
Labels: easy-to-review, area/ci, area/seccomp

#3636 ci/gha: use v3 tag for actions/cache
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci
