Repository opencontainers/runc, pull requests merged in 2022-05, with the labels that each got.

#3369 tests/int: nits and cleanups
  tests/integration/cgroups.bats
  tests/integration/checkpoint.bats
  tests/integration/create.bats
  tests/integration/delete.bats
  tests/integration/dev.bats
  tests/integration/exec.bats
  tests/integration/helpers.bash
  tests/integration/list.bats
  tests/integration/mask.bats
  tests/integration/pause.bats
  tests/integration/ps.bats
  tests/integration/run.bats
  tests/integration/start_detached.bats
  tests/integration/start_hello.bats
  tests/integration/tty.bats
  tests/integration/update.bats
  tests/integration/userns.bats
  tests/rootless.sh
Labels: area/ci

#3469 tests/int: fix a bad typo
  tests/integration/helpers.bash
Labels: easy-to-review, area/ci

#3468 Remove tun/tap from the default device rules
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/specconv/spec_linux.go
Labels: area/systemd, impact/changelog

#3471 Vagrantfile.fedora: fix build wrt new git
  Vagrantfile.fedora
Labels: area/ci, backport/done/1.1

#3472 [1.1] Make CI green again
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Vagrantfile.fedora
  libcontainer/cgroups/ebpf/devicefilter/devicefilter_test.go
  libcontainer/factory_linux.go
  libcontainer/process_linux.go
  update.go
Labels: area/ci, backport/1.1-pr

#3475 libct/cg/sd: check dbus.ErrClosed instead of isDbusError
  libcontainer/cgroups/systemd/dbus.go
Labels: area/systemd, backport/todo/1.0, backport/todo/1.1

#3477 [1.1] bump seccomp
  go.mod
  go.sum
  libcontainer/seccomp/config.go
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/specconv/spec_linux_test.go
  vendor/github.com/seccomp/libseccomp-golang/.golangci.yml
  vendor/github.com/seccomp/libseccomp-golang/.travis.yml
  vendor/github.com/seccomp/libseccomp-golang/CONTRIBUTING.md
  vendor/github.com/seccomp/libseccomp-golang/Makefile
  vendor/github.com/seccomp/libseccomp-golang/README.md
  vendor/github.com/seccomp/libseccomp-golang/SECURITY.md
  vendor/github.com/seccomp/libseccomp-golang/go.sum
  vendor/github.com/seccomp/libseccomp-golang/seccomp.go
  vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
  vendor/modules.txt
Labels: kind/dependency, backport/1.1-pr

#3476 [1.1] libct/cg/sd: check dbus.ErrClosed instead of isDbusError
  libcontainer/cgroups/systemd/dbus.go
Labels: area/systemd, backport/1.1-pr

#3480 Dockerfile,scripts/release: bump libseccomp to v2.5.4
  Dockerfile
  script/release_build.sh
Labels: easy-to-review, area/seccomp, dependencies, backport/todo/1.1

#3483 ci: drop docker layer caching from release job
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#3478 [1.1] seccomp: enosys: always return -ENOSYS for setup(2) on s390(x)
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
Labels: area/seccomp, backport/1.1-pr

#3479 [1.1] ci: drop docker layer caching from release job
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#3484 vendor: bump urfave/cli, add urfave_cli_no_docs tag
  Makefile
  go.mod
  go.sum
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/docs.go
  vendor/github.com/urfave/cli/flag.go
  vendor/modules.txt
Labels: easy-to-review, dependencies

#3482 script/seccomp.sh: check tarball sha256
  script/seccomp.sh
Labels: area/ci, area/seccomp, backport/done/1.1

#3493 [1.1] Allow mounting of /proc/sys/kernel/ns_last_pid
  libcontainer/rootfs_linux.go
  libcontainer/rootfs_linux_test.go
Labels: backport/1.1-pr

#3481 [1.1] bump libseccomp to v2.5.4, check tarball sha
  Dockerfile
  script/release_build.sh
  script/seccomp.sh
Labels: area/seccomp, dependencies, backport/1.1-pr
