Repository opencontainers/runc, pull requests merged in 2023-02, with the labels that each got.

#3460 Do not use regexp
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/factory_linux.go
Labels: kind/refactor

#3719 Disable clang-format
  .clang-format
Labels: easy-to-review

#3707 libcontainer: skip chown of /dev/null caused by fd redirection
  libcontainer/init_linux.go
  tests/integration/exec.bats
Labels: regression, backport/todo/1.1

#3730 Dockerfile: fix build wrt new git
  Dockerfile
Labels: easy-to-review, area/ci

#3731 [1.1] libcontainer: skip chown of /dev/null caused by fd redirection
  libcontainer/init_linux.go
  tests/integration/exec.bats
Labels: regression, backport/1.1-pr

#3740 tests: Fix weird error on centos-9
  libcontainer/cgroups/devices/systemd_test.go
Labels: easy-to-review, area/ci

#3573 tests: add tests for capabilities
  tests/integration/capabilities.bats
Labels: easy-to-review, area/ci

#3728 Fix runc crushes when parsing invalid JSON specification file
  spec.go
Labels: easy-to-review

#3661 Add support for umask when exec container
  libcontainer/setns_init_linux.go
  tests/integration/umask.bats
Labels: impact/changelog
