Repository opencontainers/runc, pull requests merged in 2023-03, with the labels that each got.

#3766 Add `.github/ISSUE_TEMPLATE/config.yml`
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  SECURITY.md
Labels: easy-to-review

#3767 .github/ISSUE_TEMPLATE/config.yml: fix contact links
  .github/ISSUE_TEMPLATE/config.yml
Labels: easy-to-review, area/docs

#3772 nsexec: retry unshare on EINVAL
  libcontainer/nsenter/nsexec.c
Labels: backport/todo/1.1

#3785 [1.1 backport] Prohibit /proc and /sys to be symlinks
  libcontainer/rootfs_linux.go
  tests/integration/mask.bats
Labels: impact/changelog, backport/1.1-pr

#3776 [1.1] nsexec: retry unshare on EINVAL
  libcontainer/nsenter/nsexec.c
Labels: impact/changelog, backport/1.1-pr

#3778 libct/cg/dev: skip flaky test of CentOS 7
  libcontainer/cgroups/devices/systemd_test.go
Labels: easy-to-review, area/ci, backport/todo/1.1

#3787 mountToRootfs: minor refactor
  libcontainer/rootfs_linux.go
Labels: easy-to-review, kind/refactor

#3753 Fix runc run "permission denied" when rootless
  Dockerfile
  libcontainer/eaccess_go119.go
  libcontainer/eaccess_stub.go
  libcontainer/standard_init_linux.go
  libcontainer/system/linux.go
  tests/integration/start_hello.bats
Labels: regression, backport/todo/1.1

#3798 Fix mount test
  tests/integration/mounts.bats
Labels: area/ci, backport/done/1.1

#3799 [1.1] fix mount test
  tests/integration/mounts.bats
Labels: area/ci, backport/1.1-pr

#3796 [1.1] CHANGELOG: fixes for 1.1.5
  CHANGELOG.md
  Makefile
Labels: area/ci, area/docs
