Repository opencontainers/runc, pull requests merged in 2023-10, with the labels that each got.

#4050 fix two typos
  libcontainer/seccomp/patchbpf/enosys_linux.go
  man/runc-update.8.md
Labels: easy-to-review

#4054 libct: fix a typo
  libcontainer/init_linux.go
Labels: easy-to-review

#4051 Rename root to stateDir in struct Container
  libcontainer/container_linux.go
  libcontainer/container_linux_test.go
  libcontainer/criu_linux.go
  libcontainer/factory_linux.go
  libcontainer/state_linux.go
Labels: easy-to-review, kind/refactor

#4031 docs: clarify the supported architectures (No MIPS)
  docs/spec-conformance.md
Labels: area/docs

#4055 [1.1 backport] fix typos
  libcontainer/nsenter/cloned_binary.c
  libcontainer/seccomp/patchbpf/enosys_linux.go
  man/runc-update.8.md
Labels: easy-to-review

#4056 Fix directory perms vs umask for tmpcopyup
  go.mod
  go.sum
  tests/integration/mounts.bats
  vendor/github.com/mrunalp/fileutils/fileutils.go
  vendor/github.com/mrunalp/fileutils/idtools.go
  vendor/modules.txt
Labels: backport/todo/1.1

#4060 [1.1] Fix directory perms vs umask for tmpcopyup
  go.mod
  go.sum
  tests/integration/mounts.bats
  vendor/github.com/mrunalp/fileutils/fileutils.go
  vendor/github.com/mrunalp/fileutils/idtools.go
  vendor/modules.txt
Labels: easy-to-review, backport/1.1-pr

#4064 ci: skip TestPodSkipDevicesUpdate on CentOS 7
  libcontainer/cgroups/devices/systemd_test.go
Labels: area/ci

#4073 libct/cg: support hugetlb rsvd
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/hugetlb_test.go
  libcontainer/cgroups/fs2/hugetlb.go
  tests/integration/cgroups.bats
Labels: area/cgroupv2, area/cgroupv1, backport/todo/1.1

#4079 ci/gha: fix downloading Release.key
  .github/workflows/test.yml
Labels: area/ci, backport/1.1-pr

#4081 [1.1] ci/gha: fix downloading Release.key
  .github/workflows/test.yml
Labels: area/ci, backport/1.1-pr

#4084 libct/cg: remove retry on EINTR in
  libcontainer/cgroups/file.go
Labels: easy-to-review, area/cgroupv1

#4085 CI fixes
  libcontainer/cgroups/fs/fs.go
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/cgroupv2, area/ci, area/cgroupv1

#4077 [1.1] libct/cg: support hugetlb rsvd
  libcontainer/cgroups/fs/hugetlb.go
  libcontainer/cgroups/fs/hugetlb_test.go
  libcontainer/cgroups/fs2/hugetlb.go
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
Labels: area/cgroupv2, area/cgroupv1, backport/1.1-pr

#3967 rootfs: remove --no-mount-fallback and finally fix MS_REMOUNT
  contrib/completions/bash/runc
  create.go
  libcontainer/configs/config.go
  libcontainer/configs/mount_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/specconv/spec_linux.go
  restore.go
  run.go
  tests/integration/mounts_sshfs.bats
  utils_linux.go
Labels: status/4-merge

#3972 libct/cg/stats: support misc for cgroup v2
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/misc.go
  libcontainer/cgroups/fs2/misc_test.go
  libcontainer/cgroups/stats.go
Labels: area/cgroupv2

#4010 feat: add `swapOnlyUsage` in `MemoryStats`
  CHANGELOG.md
  libcontainer/cgroups/fs/memory.go
  libcontainer/cgroups/fs/memory_test.go
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/memory_test.go
  libcontainer/cgroups/stats.go
Labels: impact/changelog
