Repository opencontainers/runc, pull requests merged in 2023-09, with the labels that each got.

#3749 [Carry #3205] libct/cg: add CFS bandwidth burst for CPU
  contrib/completions/bash/runc
  docs/spec-conformance.md
  libcontainer/cgroups/fs/cpu.go
  libcontainer/cgroups/fs/cpu_test.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs2/cpu.go
  libcontainer/configs/cgroup_linux.go
  libcontainer/specconv/spec_linux.go
  man/runc-update.8.md
  tests/integration/helpers.bash
  tests/integration/update.bats
  update.go
Labels: status/4-merge

#4020 [CI] increase memory.max in cgroups.bats
  tests/integration/cgroups.bats
Labels: easy-to-review, area/ci

#4017 Deprecate libcontainer/user, and migrate to github.com/moby/sys/user
  go.mod
  go.sum
  libcontainer/init_linux.go
  libcontainer/user/lookup_deprecated.go
  libcontainer/user/user_deprecated.go
  libcontainer/user/user_test.go
  list.go
  vendor/github.com/moby/sys/user/LICENSE
  vendor/github.com/moby/sys/user/lookup_unix.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/user/user_fuzzer.go
  vendor/modules.txt
Labels: status/4-merge

#3987 nsexec: cloned binary rework
  .github/workflows/test.yml
  .gitignore
  .golangci-extra.yml
  .golangci.yml
  Dockerfile
  Makefile
  README.md
  cc_platform.mk
  contrib/cmd/memfd-bind/README.md
  contrib/cmd/memfd-bind/memfd-bind.go
  contrib/cmd/memfd-bind/memfd-bind@.service
  libcontainer/container_linux.go
  libcontainer/dmz/.gitignore
  libcontainer/dmz/Makefile
  libcontainer/dmz/_dmz.c
  libcontainer/dmz/cloned_binary_linux.go
  libcontainer/dmz/dmz.go
  libcontainer/dmz/dmz_fallback_linux.go
  libcontainer/dmz/dmz_linux.go
  libcontainer/dmz/dmz_unsupported.go
  libcontainer/init_linux.go
  libcontainer/nsenter/cloned_binary.c
  libcontainer/nsenter/nsexec.c
  libcontainer/process.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  libcontainer/system/kernelversion/kernel_linux.go
  libcontainer/system/kernelversion/kernel_linux_test.go
  libcontainer/system/linux.go
  script/lib.sh
  script/release_build.sh
  script/seccomp.sh
  tests/integration/helpers.bash
  tests/integration/run.bats
  tests/integration/seccomp-notify-compat.bats
  tests/integration/start_hello.bats
Labels: status/4-merge

#4018 Handle kmem.limit_in_bytes removal
  libcontainer/cgroups/fs/memory.go
Labels: area/cgroupv1, backport/todo/1.1

#4028 [1.1 backport] Handle kmem.limit_in_bytes removal
  libcontainer/cgroups/fs/memory.go
Labels: status/4-merge

#4030 libct/dmz: Move comment out of the Makefile rule
  libcontainer/dmz/Makefile
Labels: easy-to-review

#4035 Update feature status in docs
  docs/spec-conformance.md
Labels: easy-to-review
