Repository opencontainers/runc, pull requests merged in 2023-11, with the labels that each got.

#4099 Skip TestWriteCgroupFileHandlesInterrupt on CentOS 7
  internal/testutil/testutil.go
  libcontainer/cgroups/devices/systemd_test.go
  libcontainer/cgroups/file_test.go
Labels: area/ci

#4107 ci/cirrus: disable selinux-dmz kludge for centos-stream-8
  .cirrus.yml
Labels: easy-to-review, area/ci

#4095 tests/int: fix flaky "runc run with tmpfs perm"
  tests/integration/run.bats
Labels: easy-to-review, area/ci, backport/todo/1.1

#4045 [feature request] *: introduce pidfd-socket flag
  .gitignore
  Makefile
  contrib/cmd/pidfd-kill/pidfd-kill.go
  create.go
  exec.go
  libcontainer/container_linux.go
  libcontainer/init_linux.go
  libcontainer/process.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  run.go
  tests/integration/helpers.bash
  tests/integration/pidfd-socket.bats
  utils_linux.go
Labels: impact/changelog, kind/feature, status/4-merge

#4102 Fix `runc kill` and `runc delete` for containers with no init and no private PID namespace
  checkpoint.go
  delete.go
  libcontainer/cgroups/utils.go
  libcontainer/container_linux.go
  libcontainer/init_linux.go
  libcontainer/state_linux.go
  tests/integration/delete.bats
  tests/integration/kill.bats
  utils_linux.go
Labels: status/4-merge
