Repository opencontainers/runc, pull requests merged in 2023-04, with the labels that each got.

#3800 CHANGELOG: forward-port 1.1.4 and 1.1.5 changes
  CHANGELOG.md
  Makefile
Labels: area/ci, area/docs

#3782 Fix systemd cgroup driver's Apply
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/factory_linux.go
  tests/integration/cgroups.bats
Labels: impact/changelog, backport/todo/1.1

#3788 cg/sd: support CPUWeight=idle (aka cpu.idle=1)
  docs/systemd.md
  libcontainer/cgroups/systemd/systemd_test.go
  libcontainer/cgroups/systemd/v2.go
  tests/integration/update.bats
Labels: area/cgroupv2, area/systemd

#3806 [1.1] Fix systemd cgroup driver's Apply (and make CI green again)
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/factory_linux.go
  tests/integration/cgroups.bats
Labels: area/ci, area/systemd, impact/changelog, backport/1.1-pr

#3814 ci/cirrus: use Go 1.19.x not 1.19
  .cirrus.yml
Labels: easy-to-review, area/ci, backport/1.1-pr

#3808 [1.1] cgroups: cpuset: fix byte order while parsing cpuset range to bits
  libcontainer/cgroups/systemd/cpuset.go
  libcontainer/cgroups/systemd/cpuset_test.go
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/systemd, backport/1.1-pr

#3817 [1.1] Fix runc run "permission denied" when rootless
  libcontainer/eaccess_go119.go
  libcontainer/eaccess_stub.go
  libcontainer/standard_init_linux.go
  libcontainer/system/linux.go
  tests/integration/start_hello.bats
Labels: regression, backport/1.1-pr

#3811 [1.1] libctr/cgroups: don't take init's cgroup into account
  libcontainer/cgroups/systemd/v1.go
Labels: area/systemd, backport/1.1-pr

#3815 bump bats-core, fix some tests, use new features
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/systemd/v1.go
  tests/integration/checkpoint.bats
  tests/integration/exec.bats
  tests/integration/helpers.bash
Labels: area/ci, area/cgroupv1, impact/changelog

#3823 [1.1] libct/cg: add misc controller to v1 drivers
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/systemd/v1.go
Labels: easy-to-review, area/cgroupv1, impact/changelog

#3824 release: add runc.keyring file
  .github/workflows/validate.yml
  Makefile
  README.md
  runc.keyring
  script/keyring_addkey.sh
  script/keyring_validate.sh
  script/release_sign.sh
Labels: backport/todo/1.1

#3834 runc-kill(8): amend the --all description
  man/runc-kill.8.md
Labels: area/docs

#3812 libct: fix a race with systemd removal
  libcontainer/container_linux.go
Labels: area/systemd, backport/todo/1.1

#3842 libct/cg/sd: use systemd version when generating device properties
  libcontainer/cgroups/devices/systemd.go
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
Labels: area/systemd, backport/todo/1.1

#3845 [1.1] libct/cg/sd: use systemd version when generating dev props
  libcontainer/cgroups/systemd/common.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
Labels: area/systemd, impact/changelog

#3838 [1.1] release: add runc.keyring file
  .github/workflows/validate.yml
  Makefile
  README.md
  runc.keyring
  script/keyring_addkey.sh
  script/keyring_validate.sh
  script/release_sign.sh
Labels: backport/1.1-pr

#3848 ci/cirrus: use vagrant from hashicorp repo, bump Fedora to 38, bump bats
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  Vagrantfile.fedora
Labels: area/ci, backport/todo/1.1

#3357 libct/cg/sd: optimize and test findDeviceGroup
  libcontainer/cgroups/devices/systemd.go
  libcontainer/cgroups/devices/systemd_test.go
Labels: area/systemd, kind/performance
