Repository opencontainers/runc, pull requests merged in 2023-07, with the labels that each got.

#3888 runc delete: call systemd's reset-failed
  libcontainer/cgroups/systemd/common.go
  tests/integration/cgroups.bats
  tests/integration/delete.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/systemd, backport/todo/1.1

#3900 libct/cg/stats: support PSI for cgroup v2
  events.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/psi.go
  libcontainer/cgroups/fs2/psi_test.go
  libcontainer/cgroups/stats.go
  tests/integration/events.bats
  tests/integration/helpers.bash
  types/events.go
Labels: status/4-merge

#3921 [1.1] libct/cg/sd/v1: do not update non-frozen cgroup after frozen failed.
  libcontainer/cgroups/systemd/v1.go
Labels: area/systemd, area/cgroupv1, backport/1.1-pr, status/4-merge

#3919 ci: bump golangci-lint to v1.53, remove fixed exception
  .github/workflows/validate.yml
  libcontainer/user/user.go
Labels: easy-to-review, area/ci

#3717 Support idmap mounts for volumes
  .gitignore
  Makefile
  contrib/cmd/fs-idmap/fs-idmap.go
  libcontainer/configs/mount_linux.go
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/container_linux.go
  libcontainer/factory_linux.go
  libcontainer/init_linux.go
  libcontainer/message_linux.go
  libcontainer/nsenter/idmap.h
  libcontainer/nsenter/nsexec.c
  libcontainer/rootfs_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/standard_init_linux.go
  tests/integration/helpers.bash
  tests/integration/idmap.bats
Labels: impact/changelog, status/4-merge

#3826 tests/int/ps: enable for rootless
  tests/integration/helpers.bash
  tests/integration/ps.bats
Labels: area/ci, area/rootless

#3947 use the length of UIDMappings/GIDMappings to check whether empty or not
  libcontainer/configs/config_linux.go
Labels: easy-to-review

#3805 Allow bind mounts of nodev,nosuid,noexec filesystems
  contrib/completions/bash/runc
  create.go
  libcontainer/configs/config.go
  libcontainer/rootfs_linux.go
  libcontainer/specconv/spec_linux.go
  restore.go
  run.go
  tests/integration/mounts_sshfs.bats
  utils_linux.go
Labels: status/4-merge

#3843 libct/cg/sd: use systemd v240+ new MAJOR:* syntax
  libcontainer/cgroups/devices/systemd.go
Labels: area/systemd, impact/changelog, status/4-merge
