Repository opencontainers/runc, pull requests merged in 2023-08, with the labels that each got.

#3949 libct/nsenter: Show better errors for idmap mounts
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review, status/4-merge

#3956 Fix some file mode bits missing when doing mount syscall
  libcontainer/mount_linux.go
  libcontainer/rootfs_linux.go
  tests/integration/run.bats
Labels: backport/todo/1.1

#3954 contrib/fs-idmap: Minor cleanups
  contrib/cmd/fs-idmap/fs-idmap.go
Labels: easy-to-review

#3961 [1.1] Fix some file mode bits missing when doing mount syscall
  libcontainer/mount_linux.go
  libcontainer/rootfs_linux.go
  tests/integration/run.bats
Labels: backport/1.1-pr

#3933 libct/cg/fs2: use file + anon + swap for usage
  CHANGELOG.md
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/memory_test.go
Labels: area/cgroupv2, impact/changelog, status/4-merge

#3960 Fix running tests under Docker/Podman and cgroup v2
  Dockerfile
  libcontainer/cgroups/file_test.go
  libcontainer/cgroups/manager/manager_test.go
  script/prepare-cgroup-v2.sh
  tests/integration/update.bats
Labels: area/cgroupv2, area/ci, backport/todo/1.1

#3816 criu checkpoint/restore: print errors from criu log
  libcontainer/container_linux.go
  libcontainer/criu_linux.go
Labels: area/checkpoint-restore, kind/feature

#3931 nsexec: cloned_binary: remove bindfd logic entirely
  libcontainer/nsenter/cloned_binary.c
Labels: status/4-merge

#3920 ci: add go 1.21, rm go 1.19, fix cirrus jobs
  .cirrus.yml
  .github/workflows/test.yml
  go.mod
Labels: area/ci, backport/todo/1.1

#3974 ci/gha: re-enable go caching
  .github/workflows/test.yml
Labels: easy-to-review, area/ci

#3385 init simplification
  init.go
  libcontainer/README.md
  libcontainer/container_linux.go
  libcontainer/init_linux.go
  libcontainer/integration/init_test.go
Labels: kind/refactor, status/4-merge

#3977 [1.1] libct/cg/fs2: use `file` + `anon` + `swap` for usage
  CHANGELOG.md
  libcontainer/cgroups/fs2/memory.go
  libcontainer/cgroups/fs2/memory_test.go
Labels: backport/1.1-pr

#3980 timens: minor cleanups
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/container_linux.go
  libcontainer/nsenter/nsexec.c
  libcontainer/specconv/spec_linux.go
  tests/integration/helpers.bash
  tests/integration/timens.bats
Labels: easy-to-review

#3982 Nsexec spring cleaning part I
  Makefile
  contrib/cmd/recvtty/recvtty.go
  libcontainer/configs/mount_linux.go
  libcontainer/criu_linux.go
  libcontainer/init_linux.go
  libcontainer/integration/execin_test.go
  libcontainer/nsenter/nsexec.c
  libcontainer/process_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/seccomp/seccomp_unsupported.go
  libcontainer/setns_init_linux.go
  libcontainer/sync.go
  libcontainer/utils/cmsg.go
  libcontainer/utils/utils_unix.go
  tty.go
Labels: kind/refactor

#3984 ci/gha: add job timeouts
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#3995 bump golangci-lint; remove nolint annotations for unix errno comparisons
  .github/workflows/validate.yml
  libcontainer/cgroups/file.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/utils.go
  libcontainer/criu_linux.go
  libcontainer/init_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/system/linux.go
  notify_socket.go
  signals.go
Labels: area/ci
