Repository opencontainers/runc, pull requests merged in 2023-06, with the labels that each got.

#3880 Fix Vagrant caching
  .cirrus.yml
Labels: area/ci, backport/todo/1.1

#3878 [1.1] bump Fedora, Vagrant, bats
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  Vagrantfile.fedora
  tests/integration/checkpoint.bats
  tests/integration/exec.bats
  tests/integration/helpers.bash
Labels: area/ci, backport/1.1-pr

#3887 man/runc: fixes
  man/runc.8.md
Labels: easy-to-review, area/docs, backport/todo/1.1

#3874 tests/int: increase num retries for oom tests
  tests/integration/events.bats
Labels: easy-to-review, area/ci, backport/todo/1.1

#3553 ci/cirrus: enable some rootless tests on cs9
  .cirrus.yml
  tests/integration/cgroups.bats
  tests/integration/delete.bats
  tests/integration/helpers.bash
Labels: area/ci, backport/todo/1.1

#3891 [1.1] tests/int: increase num retries for oom tests
  tests/integration/events.bats
Labels: easy-to-review, area/ci, backport/1.1-pr

#3896 go.mod: runtime-spec v1.1.0-rc.3
  docs/spec-conformance.md
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: easy-to-review

#3899 docs/systemd: fix a broken link
  docs/systemd.md
Labels: easy-to-review, area/docs, backport/todo/1.1

#3883 ci/gha: add space-at-eol check, fix existing issues
  .github/workflows/validate.yml
  MAINTAINERS_GUIDE.md
  NOTICE
  contrib/completions/bash/runc
  libcontainer/SPEC.md
  libcontainer/nsenter/README.md
Labels: area/ci

#3907 .codespellrc: update for 2.2.5
  .codespellrc
Labels: easy-to-review, area/ci, backport/todo/1.1

#3804 libct/cg/sd/v1: do not update non-frozen cgroup after frozen failed.
  libcontainer/cgroups/systemd/v1.go
Labels: area/systemd, area/cgroupv1, backport/todo/1.1

#3852 libct: document process.LogLevel field
  libcontainer/process.go
Labels: easy-to-review

#3909 [1.1] .codespellrc: update for 2.2.5
  .codespellrc
Labels: easy-to-review, area/ci, backport/1.1-pr

#3892 [1.1] man/runc: fixes
  man/runc.8.md
Labels: easy-to-review, area/docs, backport/1.1-pr

#3889 ci: bump shellcheck to 0.9.0, fix new SC2016 warnings
  .github/workflows/validate.yml
  tests/integration/helpers.bash
  tests/integration/hooks.bats
  tests/integration/update.bats
Labels: easy-to-review, area/ci

#3902 ci/gha: don't skip rootless+systemd on ubuntu 22.04
  .github/workflows/test.yml
Labels: easy-to-review, area/ci

#3827 libct/cg: IsCgroup2UnifiedMode: don't panic
  libcontainer/cgroups/utils.go
Labels: easy-to-review, area/cgroupv2

#3912 Fix tmpfs mode opts when dir already exists
  libcontainer/rootfs_linux.go
  tests/integration/run.bats
Labels: backport/todo/1.1

#3916 [1.1] Fix tmpfs mode opts when dir already exists
  libcontainer/rootfs_linux.go
  tests/integration/run.bats
Labels: backport/1.1-pr

#3917 [1.1] docs/systemd: fix a broken link
  docs/systemd.md
Labels: easy-to-review, area/docs, backport/1.1-pr

#3918 [1.1] ci/cirrus: enable some rootless tests on cs9
  .cirrus.yml
  tests/integration/cgroups.bats
Labels: area/ci, backport/1.1-pr
