Repository opencontainers/runc, pull requests merged in 2023-12, with the labels that each got.

#4124 *: fix several issues with namespace path handling
  .gitignore
  Makefile
  contrib/cmd/remap-rootfs/remap-rootfs.go
  libcontainer/configs/config_linux.go
  libcontainer/configs/validate/rootless.go
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/nsenter/nsexec.c
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  libcontainer/userns/userns_maps.c
  libcontainer/userns/userns_maps_linux.go
  tests/integration/delete.bats
  tests/integration/events.bats
  tests/integration/helpers.bash
  tests/integration/idmap.bats
  tests/integration/kill.bats
  tests/integration/mounts.bats
  tests/integration/run.bats
  tests/integration/timens.bats
  tests/integration/userns.bats
Labels: backport/todo/1.1, status/4-merge

#4134 specconv: temporarily allow userns path and mapping if they match
  libcontainer/configs/config.go
  libcontainer/configs/config_linux.go
  libcontainer/container_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  libcontainer/userns/userns_maps_linux.go
Labels: backport/todo/1.1

#4144 [1.1] *: fix several issues with userns path handling
  libcontainer/configs/config.go
  libcontainer/configs/config_linux.go
  libcontainer/configs/validate/rootless.go
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/container_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  libcontainer/userns/userns_maps.c
  libcontainer/userns/userns_maps_linux.go
  tests/integration/run.bats
  tests/integration/userns.bats
Labels: backport/1.1-pr

#3985 libcontainer: remove all mount logic from nsexec
  go.mod
  go.sum
  libcontainer/apparmor/apparmor_linux.go
  libcontainer/cgroups/cgroups_test.go
  libcontainer/cgroups/file.go
  libcontainer/cgroups/fs2/defaultpath.go
  libcontainer/cgroups/v1_utils.go
  libcontainer/configs/mount.go
  libcontainer/configs/mount_linux.go
  libcontainer/configs/namespaces_linux.go
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/container_linux.go
  libcontainer/criu_linux.go
  libcontainer/factory_linux.go
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/message_linux.go
  libcontainer/mount_linux.go
  libcontainer/nsenter/idmap.h
  libcontainer/nsenter/nsexec.c
  libcontainer/process_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/rootfs_linux_test.go
  libcontainer/specconv/spec_linux.go
  libcontainer/standard_init_linux.go
  libcontainer/sync.go
  libcontainer/userns/usernsfd_linux.go
  libcontainer/userns/usernsfd_linux_test.go
  libcontainer/utils/utils.go
  libcontainer/utils/utils_unix.go
  tests/integration/idmap.bats
  tests/integration/mounts.bats
  utils_linux.go
  vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
  vendor/modules.txt
Labels: status/4-merge

#4157 libct: Improve error msg when idmap is not supported
  libcontainer/mount_linux.go
Labels: easy-to-review
