Repository opencontainers/runc, pull requests merged in 2023-05, with the labels that each got.

#3851 deps: bump urfave/cli
  go.mod
  go.sum
  vendor/github.com/urfave/cli/.gitignore
  vendor/github.com/urfave/cli/LICENSE
  vendor/github.com/urfave/cli/README.md
  vendor/github.com/urfave/cli/app.go
  vendor/github.com/urfave/cli/appveyor.yml
  vendor/github.com/urfave/cli/command.go
  vendor/modules.txt
Labels: easy-to-review, dependencies

#3830 go.mod: runtime-spec v1.1.0-rc.2
  docs/spec-conformance.md
  features.go
  go.mod
  go.sum
  types/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: easy-to-review, dependencies, go

#3870 ci/gha: cross-i386: fix build, rm kludges
  .github/workflows/test.yml
Labels: easy-to-review, area/ci

#3822 ci/gha: disable double caching
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#3854 Some init code refactoring
  libcontainer/factory_linux.go
  libcontainer/init_linux.go
  libcontainer/integration/execin_test.go
  libcontainer/integration/init_test.go
Labels: kind/refactor

#3879 [1.1] init: do not print environment variable value
  libcontainer/init_linux.go
Labels: backport/1.1-pr

#3877 [1.1] libct: fix a race with systemd removal
  libcontainer/container_linux.go
Labels: area/systemd, backport/1.1-pr
