Repository opencontainers/runc, pull requests merged in 2024-08, with the labels that each got.

#4369 Fix link to gvariant documentation in systemd docs.
  docs/systemd.md
Labels: easy-to-review, backport/todo/1.1

#4371 libct/int/seccomp_test: simplify exit code checks
  libcontainer/integration/seccomp_test.go
Labels: easy-to-review

#4372 [1.1] Add Go 1.23, drop 1.21
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
Labels: area/ci, backport/1.1-pr

#4374 Fix cpu burst test failure on newer kernels
  tests/integration/helpers.bash
Labels: area/ci

#4360 Add Go 1.23, drop 1.21
  .cirrus.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  go.mod
  libcontainer/cgroups/fs/blkio_test.go
  libcontainer/configs/config_test.go
Labels: area/ci, backport/done/1.1

#4370 Revert "allow overriding VERSION value in Makefile" and add EXTRA_VERSION
  Makefile
  README.md
Labels: easy-to-review, impact/changelog, backport/todo/1.1

#4377 mv contrib/cmd tests/cmd (except memfd-bind)
  .gitignore
  Makefile
  docs/terminals.md
  tests/cmd/fs-idmap/fs-idmap.go
  tests/cmd/pidfd-kill/pidfd-kill.go
  tests/cmd/recvtty/recvtty.go
  tests/cmd/remap-rootfs/remap-rootfs.go
  tests/cmd/sd-helper/helper.go
  tests/cmd/seccompagent/README.md
  tests/cmd/seccompagent/gen-seccomp-example-cfg.sh
  tests/cmd/seccompagent/seccompagent.go
  tests/cmd/seccompagent/unsupported.go
  tests/integration/helpers.bash
  tests/integration/seccomp-notify.bats
Labels: easy-to-review

#4376 ci/gha: add all-done jobs
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: area/ci

#4382 [1.1] Revert "allow overriding VERSION value in Makefile" and add EXTRA_VERSION
  Makefile
  README.md
Labels: impact/changelog, backport/1.1-pr

#4380 Makefile: Don't read COMMIT, BUILDTAGS, EXTRA_BUILDTAGS from env vars
  Makefile
Labels: impact/changelog
