Repository opencontainers/runc, pull requests merged in 2024-10, with the labels that each got.

#4423 [1.1]: Increase memory.max in cgroups.bats
  tests/integration/cgroups.bats
Labels: backport/1.1-pr

#4417 runc run: fix mount leak
  libcontainer/rootfs_linux.go
Labels: backport/done/1.1

#4430 go: update github.com/cyphar/filepath-securejoin to v0.3.4
  go.mod
  go.sum
  vendor/github.com/cyphar/filepath-securejoin/CHANGELOG.md
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/doc.go
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/cyphar/filepath-securejoin/openat_linux.go
  vendor/github.com/cyphar/filepath-securejoin/procfs_linux.go
  vendor/github.com/cyphar/filepath-securejoin/testing_mocks_linux.go
  vendor/modules.txt
Labels: easy-to-review

#4428 memfd-bind: fixup systemd unit file and README
  contrib/cmd/memfd-bind/README.md
  contrib/cmd/memfd-bind/memfd-bind@.service
Labels: easy-to-review

#4444 dmz: cloned binary: set +x permissions when creating regular tmpfile
  libcontainer/dmz/cloned_binary_linux.go
Labels: easy-to-review

#4455 tests/int: skip "update memory vs CheckBeforeUpdate" on EL9
  tests/integration/update.bats
Labels: area/ci

#4456 Misc tests/int cleanups
  tests/integration/helpers.bash
  tests/integration/run.bats
  tests/integration/selinux.bats
Labels: area/ci

#4429 libct/cap: no need to load capabilities
  libcontainer/capabilities/capabilities.go
Labels: easy-to-review

#4452 fix an error caused by fd reuse race when starting runc init
  libcontainer/container_linux.go
Labels: kind/bug

#4465 libct: rm x/sys/execabs usage
  libcontainer/container_linux.go
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/modules.txt
Labels: easy-to-review, kind/refactor, kind/dependency, backport/todo/1.2

#4471 ci: use Go 1.23
  .cirrus.yml
  .github/workflows/validate.yml
  Dockerfile
Labels: easy-to-review

#4473 libct/nsenter: become root after joining userns
  libcontainer/nsenter/nsexec.c
  tests/integration/userns.bats
Labels: area/selinux, area/userns, backport/1.2-todo

#4477 [1.2] libct/nsenter: become root after joining userns
  libcontainer/nsenter/nsexec.c
  tests/integration/userns.bats
Labels: area/selinux, area/userns, backport/1.2-pr

#4484 docs: remove prompt symbols from shell snippets
  contrib/cmd/memfd-bind/README.md
  docs/cgroup-v2.md
  docs/terminals.md
  tests/integration/README.md
Labels: easy-to-review, area/docs, backport/1.2-todo

#4482 drop runc-dmz solution according to overlay solution
  .github/workflows/test.yml
  .golangci-extra.yml
  .golangci.yml
  Makefile
  README.md
  cc_platform.mk
  contrib/cmd/memfd-bind/README.md
  docs/experimental.md
  libcontainer/container_linux.go
  libcontainer/dmz/Makefile
  libcontainer/dmz/README.md
  libcontainer/dmz/_dmz.c
  libcontainer/dmz/binary/.gitignore
  libcontainer/dmz/binary/dummy-file.txt
  libcontainer/dmz/dmz.go
  libcontainer/dmz/dmz_fallback_linux.go
  libcontainer/dmz/dmz_linux.go
  libcontainer/dmz/dmz_unsupported.go
  libcontainer/dmz/linux/README.md
  libcontainer/dmz/linux/stat.h
  libcontainer/dmz/nolibc/arch-aarch64.h
  libcontainer/dmz/nolibc/arch-arm.h
  libcontainer/dmz/nolibc/arch-i386.h
  libcontainer/dmz/nolibc/arch-loongarch.h
  libcontainer/dmz/nolibc/arch-mips.h
  libcontainer/dmz/nolibc/arch-powerpc.h
  libcontainer/dmz/nolibc/arch-riscv.h
  libcontainer/dmz/nolibc/arch-s390.h
  libcontainer/dmz/nolibc/arch-x86_64.h
  libcontainer/dmz/nolibc/arch.h
  libcontainer/dmz/nolibc/compiler.h
  libcontainer/dmz/nolibc/crt.h
  libcontainer/dmz/nolibc/ctype.h
  libcontainer/dmz/nolibc/errno.h
  libcontainer/dmz/nolibc/nolibc.h
  libcontainer/dmz/nolibc/signal.h
  libcontainer/dmz/nolibc/stackprotector.h
  libcontainer/dmz/nolibc/std.h
  libcontainer/dmz/nolibc/stdint.h
  libcontainer/dmz/nolibc/stdio.h
  libcontainer/dmz/nolibc/stdlib.h
  libcontainer/dmz/nolibc/string.h
  libcontainer/dmz/nolibc/sys.h
  libcontainer/dmz/nolibc/time.h
  libcontainer/dmz/nolibc/types.h
  libcontainer/dmz/nolibc/unistd.h
  libcontainer/dmz/xstat.h
  libcontainer/init_linux.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  tests/integration/run.bats
  tests/integration/selinux.bats
Labels: impact/changelog, backport/1.2-todo

#4488 [1.2] drop runc-dmz solution according to overlay solution
  .github/workflows/test.yml
  .golangci-extra.yml
  .golangci.yml
  Makefile
  README.md
  cc_platform.mk
  contrib/cmd/memfd-bind/README.md
  docs/experimental.md
  libcontainer/container_linux.go
  libcontainer/dmz/Makefile
  libcontainer/dmz/README.md
  libcontainer/dmz/_dmz.c
  libcontainer/dmz/binary/.gitignore
  libcontainer/dmz/binary/dummy-file.txt
  libcontainer/dmz/dmz.go
  libcontainer/dmz/dmz_fallback_linux.go
  libcontainer/dmz/dmz_linux.go
  libcontainer/dmz/dmz_unsupported.go
  libcontainer/dmz/linux/README.md
  libcontainer/dmz/linux/stat.h
  libcontainer/dmz/nolibc/arch-aarch64.h
  libcontainer/dmz/nolibc/arch-arm.h
  libcontainer/dmz/nolibc/arch-i386.h
  libcontainer/dmz/nolibc/arch-loongarch.h
  libcontainer/dmz/nolibc/arch-mips.h
  libcontainer/dmz/nolibc/arch-powerpc.h
  libcontainer/dmz/nolibc/arch-riscv.h
  libcontainer/dmz/nolibc/arch-s390.h
  libcontainer/dmz/nolibc/arch-x86_64.h
  libcontainer/dmz/nolibc/arch.h
  libcontainer/dmz/nolibc/compiler.h
  libcontainer/dmz/nolibc/crt.h
  libcontainer/dmz/nolibc/ctype.h
  libcontainer/dmz/nolibc/errno.h
  libcontainer/dmz/nolibc/nolibc.h
  libcontainer/dmz/nolibc/signal.h
  libcontainer/dmz/nolibc/stackprotector.h
  libcontainer/dmz/nolibc/std.h
  libcontainer/dmz/nolibc/stdint.h
  libcontainer/dmz/nolibc/stdio.h
  libcontainer/dmz/nolibc/stdlib.h
  libcontainer/dmz/nolibc/string.h
  libcontainer/dmz/nolibc/sys.h
  libcontainer/dmz/nolibc/time.h
  libcontainer/dmz/nolibc/types.h
  libcontainer/dmz/nolibc/unistd.h
  libcontainer/dmz/xstat.h
  libcontainer/init_linux.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  tests/integration/run.bats
  tests/integration/selinux.bats
Labels: impact/changelog, backport/1.2-pr

#4489 CHANGELOG: add (forward-port) v1.1.15 changes
  CHANGELOG.md
Labels: backport/1.2-todo

#4490 Post overlay addition and dmz removal nits
  libcontainer/process.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  script/check-config.sh
Labels: easy-to-review, backport/1.2-todo
