Repository opencontainers/runc, pull requests merged in 2024-02, with the labels that each got.

#4198 [ci] update go version to 1.21 in cirrus ci
  .cirrus.yml
Labels: area/ci

#4187 tests/int: use gawk where needed
  tests/integration/helpers.bash
Labels: easy-to-review, area/ci

#4202 ci/golangci-lint: add checks permission
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#4205 Fixed spelling mistake in the Makefile at .PHONY vendor
  Makefile
Labels: easy-to-review
