Repository opencontainers/runc, pull requests merged in 2024-04, with the labels that each got.

#4234 [hotfix] nsenter: refuse to build with Go 1.22
  .github/workflows/test.yml
  CHANGELOG.md
  libcontainer/nsenter/nsenter_go122.go
Labels: impact/changelog

#4241 [1.1] CI fixes and misc backports
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  script/release_build.sh
  script/seccomp.sh
  tests/integration/run.bats
Labels: backport/1.1-pr

#4238 ci/test: exclude some runc_nodmz jobs
  .github/workflows/test.yml
Labels: area/ci

#3923 Set temporary single CPU affinity before cgroup cpuset transition.
  docs/isolated-cpu-affinity-transition.md
  features.go
  libcontainer/cgroups/cgroups.go
  libcontainer/cgroups/fs/fs.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/systemd/v1.go
  libcontainer/cgroups/systemd/v2.go
  libcontainer/container_linux_test.go
  libcontainer/process_linux.go
  libcontainer/process_linux_test.go
  libcontainer/system/kernelparam/lookup.go
  libcontainer/system/kernelparam/lookup_test.go
  tests/integration/exec.bats
  tests/integration/helpers.bash
Labels: status/2-code-review

#4142 CI: add actuated-arm64
  .github/workflows/test.yml
  .github/workflows/validate.yml
  README.md
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
  tests/integration/testdata/seccomp_syscall_test1.c
  tests/integration/testdata/seccomp_syscall_test1.json
Labels: area/ci

#4252 ci/actuated: re-enable CRIU tests
  .github/workflows/test.yml
  tests/integration/checkpoint.bats
  tests/integration/helpers.bash
Labels: area/ci, area/checkpoint-restore

#4256 Vagrantfile.fedora: bump Fedora to 39
  Vagrantfile.fedora
Labels: easy-to-review, area/ci

#4261 [1.1] Vagrantfile.fedora: bump Fedora to 39
  Vagrantfile.fedora
Labels: easy-to-review, area/ci, backport/1.1-pr

#4255 ci/gha: bump golangci-lint[-action]
  .github/workflows/validate.yml
  libcontainer/init_linux.go
Labels: easy-to-review, area/ci

#4257 [1.1] libcontainer: force apps to think fips is enabled/disabled for testing
  libcontainer/rootfs_linux.go
  libcontainer/rootfs_linux_test.go
Labels: backport/1.1-pr

#4260 tests/int/tty: increase the timeout
  tests/integration/tty.bats
Labels: easy-to-review, area/ci

#4264 [ci] use go mod instead of go get in spec.bats
  tests/integration/spec.bats
Labels: area/ci
