Repository opencontainers/runc, pull requests merged in 2024-03, with the labels that each got.

#4174 Disable runc-dmz by default
  Makefile
  README.md
  contrib/cmd/memfd-bind/README.md
  libcontainer/dmz/dmz_linux.go
  tests/integration/exec.bats
  tests/integration/run.bats
  tests/integration/selinux.bats
Labels: status/2-code-review

#4222 fix runc-dmz bin path error in Makefile
  Makefile
Labels: kind/bug, easy-to-review

#4179 tests/int: fix flaky kill tests
  tests/integration/delete.bats
  tests/integration/helpers.bash
  tests/integration/kill.bats
Labels: area/ci

#4224 Remove dependabot ignore
  .github/dependabot.yml
  go.mod
  go.sum
  vendor/modules.txt
Labels: easy-to-review

#4223 build: update libseccomp to v2.5.5
  Dockerfile
  script/release_build.sh
  script/seccomp.sh
Labels: easy-to-review, area/seccomp, backport/todo/1.1

#4219 seccomp: patchbpf: always include native architecture in stub
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
Labels: area/seccomp
