Repository opencontainers/runc, pull requests merged in 2024-12, with the labels that each got.

#4492 nsenter: implement a two-stage join for setns
  Makefile
  libcontainer/nsenter/nsexec.c
  tests/integration/userns.bats
Labels: kind/bug, area/nsenter, area/userns

#4549 deps: update to github.com/cyphar/filepath-securejoin@v0.3.5
  go.mod
  go.sum
  vendor/github.com/cyphar/filepath-securejoin/CHANGELOG.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/mkdir_linux.go
  vendor/modules.txt
Labels: backport/1.2-todo

#4548 cgroups: ebpf: use link.Anchor to check for BPF_F_REPLACE support
  libcontainer/cgroups/devices/ebpf_linux.go
Labels: backport/1.2-todo

#4551 [1.2] cgroups: ebpf: use link.Anchor to check for BPF_F_REPLACE support
  libcontainer/cgroups/devices/ebpf_linux.go
Labels: backport/1.2-pr

#4546 Add `runc_nocriu` build tag to opt out of c/r
  .github/workflows/validate.yml
  README.md
  checkpoint.go
  libcontainer/criu_disabled_linux.go
  libcontainer/criu_linux.go
  libcontainer/criu_opts_linux.go
Labels: area/checkpoint-restore

#4554 [1.2] keyring: update @kolyshkin key expiry
  runc.keyring
Labels: backport/1.2-pr

#4555 Re-add tun/tap to default device rules
  libcontainer/cgroups/devices/devicefilter_test.go
  libcontainer/specconv/spec_linux.go
Labels: backport/1.2-todo

#4556 [1.2] Re-add tun/tap to default device rules
  libcontainer/cgroups/devices/devicefilter_test.go
  libcontainer/specconv/spec_linux.go
Labels: backport/1.2-pr

#4561 GHA CI bumps
  .github/workflows/validate.yml
Labels: area/ci, backport/1.2-todo

#4562 remove broken fuzzer from oss-fuzz build script
  tests/fuzzing/oss_fuzz_build.sh
Labels: easy-to-review

#4312 refactor init and setns process
  libcontainer/container_linux.go
  libcontainer/process_linux.go
Labels: easy-to-review, kind/refactor

#4433 libct: add/use configs.HasHook
  libcontainer/configs/config.go
  libcontainer/container_linux.go
  libcontainer/criu_linux.go
  libcontainer/process_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/standard_init_linux.go
Labels: kind/performance

#4459 Fixups to scheduler/priority settings
  libcontainer/configs/config.go
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/init_linux.go
  libcontainer/process_linux.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  utils_linux.go
Labels: kind/refactor

#4572 Fix `go.mod` link in README.md
  README.md
Labels: easy-to-review, area/docs
