Repository opencontainers/runc, pull requests merged in 2024-11, with the labels that each got.

#4493 [1.2] CHANGELOG: add (forward-port) v1.1.15 changes
  CHANGELOG.md
Labels: backport/1.2-pr

#4357 runc update: fix updating swap for cgroup v2
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
Labels: kind/bug, backport/1.2-todo

#4501 [1.2] runc update: fix updating swap for cgroup v2
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
Labels: backport/1.2-pr

#4494 [1.2] Post overlay addition and dmz removal nits
  libcontainer/process.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  script/check-config.sh
Labels: easy-to-review, backport/1.2-pr

#4505 CI: bump Fedora 40 -> 41
  Vagrantfile.fedora
Labels: area/ci, backport/1.2-todo

#4514 ci: temporary set vagrant to 2.4.1-1
  .cirrus.yml
Labels: area/ci

#4509 dmz: overlay: minor fixups
  README.md
  contrib/cmd/memfd-bind/README.md
  libcontainer/dmz/overlayfs_linux.go
Labels: backport/1.2-todo

#4511 ci: rm "skip on CentOS 7" kludges
  internal/testutil/testutil.go
  libcontainer/cgroups/devices/systemd_test.go
  libcontainer/cgroups/file_test.go
Labels: kind/refactor

#4528 [1.2] CI: bump Fedora 40 -> 41
  Vagrantfile.fedora
Labels: area/ci, backport/1.2-pr

#4529 Revert "Temporary set vagrant to 2.4.1-1"
  .cirrus.yml
Labels: easy-to-review, area/ci

#4526 libct/cg: add test for remove a non-existent dir in a ro mount point
  libcontainer/cgroups/utils_test.go
Labels: area/ci

#4531 [1.2] runc delete: fix for rootless cgroup + ro cgroupfs
  libcontainer/cgroups/utils.go
  libcontainer/cgroups/utils_test.go
Labels: regression, backport/1.2-pr

#4530 [1.2] dmz: overlay: minor fixups
  README.md
  contrib/cmd/memfd-bind/README.md
  libcontainer/dmz/overlayfs_linux.go
Labels: backport/1.2-pr
