Repository opencontainers/runc, pull requests merged in 2024-05, with the labels that each got.

#4251 tests/int/checkpoint: rm double logging
  tests/integration/checkpoint.bats
Labels: easy-to-review, area/ci, area/checkpoint-restore

#4270 [1.1] allow overriding VERSION value in Makefile
  Makefile
Labels: backport/1.1-pr

#4275 ci/gha: bump golangci-lint-action from 5 to 6
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci, dependencies, github_actions

#4268 Remove unused system.Execv
  libcontainer/standard_init_linux.go
  libcontainer/system/linux.go
Labels: easy-to-review

#4265 Fix set nofile rlimit error
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/process_linux.go
  libcontainer/setns_init_linux.go
  libcontainer/system/linux.go
  tests/integration/rlimits.bats
Labels: backport/todo/1.1

#4279 .cirrus.yml: rm FIXME from rootless fs on CentOS 7
  .cirrus.yml
Labels: easy-to-review, area/ci

#4282 Add a correct GoDoc format comment for ClearRlimitNofileCache
  libcontainer/system/linux.go
Labels: easy-to-review

#4231 [1.1] runc list: fix race with runc delete
  list.go
Labels: backport/1.1-pr

#4276 fix checkpoint/restore tests on actuated-arm64
  libcontainer/criu_linux.go
  libcontainer/integration/checkpoint_test.go
Labels: area/ci, area/checkpoint-restore

#4277 [1.1] Fix set nofile rlimit error
  go.mod
  go.sum
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/process_linux.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  libcontainer/system/linux.go
  libcontainer/system/rlimit_go119.go
  libcontainer/system/rlimit_stub.go
  tests/integration/rlimits.bats
Labels: backport/1.1-pr

#4258 libct/cg/fs: fix setting rt_period vs rt_runtime
  libcontainer/cgroups/fs/cpu.go
  tests/integration/update.bats
Labels: area/cgroupv1, backport/todo/1.1

#4284 [1.1] libct/cg/fs: fix setting rt_period vs rt_runtime
  libcontainer/cgroups/fs/cpu.go
  tests/integration/update.bats
Labels: area/cgroupv1, backport/1.1-pr
