Repository opencontainers/runc, pull requests merged in 2024-06, with the labels that each got.

#4296 Dockerfile: bump Debian to 12, Go to 1.21
  Dockerfile
Labels: easy-to-review, dependencies

#4295 libct/cg/dev: fix TestSetV1Allow panic
  libcontainer/cgroups/devices/v1_test.go
Labels: area/ci

#4290 Rlimit cache rework for Go 1.23+
  libcontainer/init_linux.go
  libcontainer/system/linux.go
  libcontainer/system/rlimit_linux.go
  libcontainer/system/rlimit_linux_go122.go
Labels: backport/todo/1.1

#4301 ci: pin codespell
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci, backport/todo/1.1

#4298 tests/int/scheduler: require smp
  tests/integration/scheduler.bats
Labels: easy-to-review, area/ci

#4300 [1.1] Fix codespell warnings
  .github/workflows/validate.yml
  features.go
  utils_linux.go
Labels: easy-to-review, backport/1.1-pr

#4304 ci: workaround for centos stream 8 being EOLed
  .cirrus.yml
Labels: easy-to-review, area/ci, backport/todo/1.1

#4305 [1.1] ci: workaround for centos stream 8 being EOLed
  .cirrus.yml
Labels: backport/1.1-pr

#4299 [1.1] libct/system: ClearRlimitNofileCache for go 1.23
  libcontainer/init_linux.go
  libcontainer/system/rlimit_linux.go
  libcontainer/system/rlimit_linux_go122.go
  libcontainer/system/rlimit_stub.go
Labels: backport/1.1-pr

#4188 tests/int: swap-related fixes
  libcontainer/cgroups/fs2/memory.go
  tests/integration/cgroups.bats
  tests/integration/helpers.bash
  tests/integration/update.bats
Labels: area/cgroupv2, area/ci

#4189 script/*: fix gpg usage wrt keyboxd
  script/keyring_validate.sh
  script/release_sign.sh
Labels: area/ci

#4292 Stop blacklisting Go 1.22+, drop Go < 1.21 support, use Go 1.22 in CI
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Dockerfile
  README.md
  go.mod
  go.sum
  libcontainer/cgroups/utils.go
  libcontainer/container_linux.go
  libcontainer/eaccess_go119.go
  libcontainer/eaccess_stub.go
  libcontainer/nsenter/nsenter_go122.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
Labels: backport/done/1.1

#4311 fix a debug msg for user ns in nsexec
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review

#4186 libct/cg: write unified resources line by line
  libcontainer/cgroups/file.go
  libcontainer/cgroups/file_test.go
  libcontainer/cgroups/fs2/fs2.go
  tests/integration/cgroups.bats
Labels: area/cgroupv2

#4313 [1.1] Support Go 1.22, bump some CI deps
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Dockerfile
  README.md
  libcontainer/user/user.go
  tests/integration/spec.bats
Labels: backport/1.1-pr

#4315 [1.1] fix a debug msg for user ns in nsexec
  libcontainer/nsenter/nsexec.c
Labels: easy-to-review, backport/1.1-pr

#4316 [1.1] script/*: fix gpg usage wrt keyboxd
  script/keyring_validate.sh
  script/release_sign.sh
Labels: backport/1.1-pr

#4320 Some nits I found from older PRs
  exec.go
  script/keyring_validate.sh
Labels: easy-to-review

#4321 update changelog after v1.1.13 released
  CHANGELOG.md
Labels: easy-to-review, area/docs

#4322 Put the changelog of v1.1.13 after v1.2.0-rc.1
  CHANGELOG.md
Labels: easy-to-review

#4319 Try to delete exec fifo file when failure in creation
  libcontainer/container_linux.go
Labels: easy-to-review
