Repository opencontainers/runc, pull requests merged in 2024-01, with the labels that each got.

#4139 remove remap-rootfs bin when running make clean
  Makefile
Labels: easy-to-review

#4159 update spec-conformance.md(rsvd hugetlb cgroup and idmapped-mounts)
  docs/spec-conformance.md
Labels: area/docs

#4146 TestCheckpoint: skip on ErrCriuMissingFeatures
  libcontainer/criu_linux.go
  libcontainer/integration/checkpoint_test.go
Labels: easy-to-review, area/ci, area/checkpoint-restore

#4176 keyring: update key expiries
  runc.keyring
Labels: easy-to-review, backport/todo/1.1

#4177 [1.1] keyring: update key expiries
  runc.keyring
Labels: easy-to-review, backport/1.1-pr
