Repository opencontainers/runc, pull requests merged in 2024-07, with the labels that each got.

#4329 remove pre-go1.17 build-tags
  contrib/cmd/seccompagent/seccompagent.go
  contrib/cmd/seccompagent/unsupported.go
  libcontainer/apparmor/apparmor_unsupported.go
  libcontainer/capabilities/capabilities.go
  libcontainer/capabilities/capabilities_unsupported.go
  libcontainer/configs/cgroup_unsupported.go
  libcontainer/configs/configs_fuzzer.go
  libcontainer/configs/mount_unsupported.go
  libcontainer/configs/namespaces_syscall.go
  libcontainer/configs/namespaces_syscall_unsupported.go
  libcontainer/configs/namespaces_unsupported.go
  libcontainer/devices/device_unix.go
  libcontainer/devices/device_unix_test.go
  libcontainer/dmz/dmz_linux.go
  libcontainer/dmz/dmz_unsupported.go
  libcontainer/integration/seccomp_test.go
  libcontainer/nsenter/nsenter.go
  libcontainer/nsenter/nsenter_gccgo.go
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/patchbpf/enosys_linux_test.go
  libcontainer/seccomp/patchbpf/enosys_unsupported.go
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/seccomp/seccomp_unsupported.go
  libcontainer/system/linux.go
  libcontainer/userns/userns_fuzzer.go
  libcontainer/userns/userns_unsupported.go
  libcontainer/utils/utils_unix.go
Labels: easy-to-review, kind/refactor

#4330 libct/userns: assorted (godoc) improvements
  libcontainer/userns/userns.go
  libcontainer/userns/userns_linux.go
  libcontainer/userns/userns_linux_fuzzer.go
  libcontainer/userns/userns_unsupported.go
Labels: kind/refactor

#4335 ci/cirrus: rm CentOS 7; add Almalinux 8/9
  .cirrus.yml
Labels: backport/todo/1.1

#4331 libct/userns: split userns detection from internal userns code
  libcontainer/integration/exec_test.go
  libcontainer/internal/userns/userns_maps.c
  libcontainer/internal/userns/userns_maps_linux.go
  libcontainer/internal/userns/usernsfd_linux.go
  libcontainer/internal/userns/usernsfd_linux_test.go
  libcontainer/mount_linux.go
  libcontainer/process_linux.go
  libcontainer/specconv/spec_linux.go
Labels: kind/refactor

#4336 [1.1] ci/cirrus: switch from CentOS to Almalinux
  .cirrus.yml
Labels: backport/1.1-pr

#4334 [1.1] rootfs: fix 'can we mount on top of /proc' check
  libcontainer/container_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/rootfs_linux_test.go
Labels: backport/1.1-pr

#4332 ci/gha: add go-fix job
  .github/workflows/validate.yml
Labels: easy-to-review, area/ci

#4337 Revert "libcontainer: seccomp: pass around *os.File for notifyfd"
  libcontainer/init_linux.go
  libcontainer/seccomp/patchbpf/enosys_linux.go
  libcontainer/seccomp/seccomp_linux.go
  libcontainer/seccomp/seccomp_unsupported.go
  tests/integration/seccomp-notify.bats
Labels: area/seccomp

#4353 document how to build under alpine
  README.md
Labels: area/docs, status/4-merge

#4359 rootfs: consolidate mountpoint creation logic
  libcontainer/criu_linux.go
  libcontainer/rootfs_linux.go
  libcontainer/utils/utils_unix.go
Labels: backport/todo/1.1
