Repository opencontainers/runc, pull requests merged in 2025-02, with the labels that each got.

#4609 CI: fix criu-dev compile
  .github/workflows/test.yml
Labels: easy-to-review, area/ci, backport/1.2-done

#4611 [1.2] CI: fix criu-dev compile
  .github/workflows/test.yml
Labels: area/ci, backport/1.2-pr

#4608 [1.2] deps: update to github.com/cyphar/filepath-securejoin@v0.4.1
  go.mod
  go.sum
  libcontainer/utils/utils_unix.go
  vendor/github.com/cyphar/filepath-securejoin/CHANGELOG.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/gocompat_errors_go120.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_errors_unsupported.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_generics_go121.go
  vendor/github.com/cyphar/filepath-securejoin/gocompat_generics_unsupported.go
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/cyphar/filepath-securejoin/lookup_linux.go
  vendor/github.com/cyphar/filepath-securejoin/mkdir_linux.go
  vendor/github.com/cyphar/filepath-securejoin/openat2_linux.go
  vendor/github.com/cyphar/filepath-securejoin/procfs_linux.go
  vendor/modules.txt
Labels: backport/1.2-pr

#3999 Remove /etc/passwd and /etc/group parsing on runc run/exec
  CHANGELOG.md
  libcontainer/container_linux.go
  libcontainer/env.go
  libcontainer/env_test.go
  libcontainer/init_linux.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/process.go
  libcontainer/setns_init_linux.go
  libcontainer/standard_init_linux.go
  list.go
  tests/integration/exec.bats
  utils_linux.go
Labels: status/2-code-review

#4612 libct/cg/sd: set the DeviceAllow property before DevicePolicy
  libcontainer/cgroups/devices/systemd.go
  tests/integration/dev.bats
Labels: area/systemd, backport/1.2-done

#4616 libc/int/userns: add build tag to C file
  libcontainer/internal/userns/userns_maps_linux.c
Labels: backport/1.2-todo

#4615 [1.2] libct/cg/sd: set the DeviceAllow property before DevicePolicy
  libcontainer/cgroups/devices/systemd.go
  tests/integration/dev.bats
Labels: area/systemd, backport/1.2-pr

#4619 [1.2] libc/int/userns: add build tag to C file
  libcontainer/internal/userns/userns_maps_linux.c
Labels: backport/1.2-pr

#4592 Improvements to how `runc exec` is handled
  exec.go
  libcontainer/container_linux.go
  utils_linux.go
Labels: easy-to-review

#4629 release: explicitly set --keyserver in release signing scripts
  script/release_sign.sh
Labels: backport/1.2-todo

#4470 Use strings.Cut and strings.CutPrefix where possible
  exec.go
  libcontainer/cgroups/devices/systemd.go
  libcontainer/cgroups/file.go
  libcontainer/cgroups/fs/cpuacct.go
  libcontainer/cgroups/fs/cpuacct_test.go
  libcontainer/cgroups/fs/cpuset.go
  libcontainer/cgroups/fs2/defaultpath.go
  libcontainer/cgroups/fs2/freezer.go
  libcontainer/cgroups/fs2/fs2.go
  libcontainer/cgroups/fs2/psi.go
  libcontainer/cgroups/fscommon/rdma.go
  libcontainer/cgroups/fscommon/utils.go
  libcontainer/cgroups/systemd/user.go
  libcontainer/cgroups/utils.go
  libcontainer/configs/validate/rootless.go
  libcontainer/specconv/spec_linux.go
  libcontainer/utils/utils.go
Labels: kind/refactor

#4584 Misc nits to tests/integration
  tests/integration/hooks_so.bats
  tests/integration/tty.bats
Labels: area/ci

#4634 CI: gha: rm ubuntu-20.04
  .github/workflows/test.yml
Labels: area/ci, backport/1.2-todo

#4637 Retry direct unix package calls if observing EINTR
  libcontainer/notify_v2_linux.go
  libcontainer/sync_unix.go
  libcontainer/utils/cmsg.go
Labels: backport/1.2-todo

#4593 tests/int: add hooks argv[0] test
  tests/integration/hooks.bats
Labels: easy-to-review, area/ci

#4643 libcontainer: rename dmz -> exeseal
  contrib/cmd/memfd-bind/memfd-bind.go
  libcontainer/container_linux.go
  libcontainer/exeseal/cloned_binary_linux.go
  libcontainer/exeseal/overlayfs_linux.go
  libcontainer/process.go
  tests/integration/run.bats
Labels: easy-to-review

#4641 exeseal: do not use F_SEAL_FUTURE_WRITE
  libcontainer/exeseal/cloned_binary_linux.go
Labels: backport/1.2-todo

#4636 libct: don't send config to nsexec when joining an existing timens
  libcontainer/container_linux.go
  tests/integration/timens.bats
Labels: backport/1.2-todo

#4648 [1.2] Add Go 1.24, drop ubuntu 20.04
  .cirrus.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Dockerfile
Labels: backport/1.2-pr

#4646 [1.2] libct/system: rm Fexecve
  libcontainer/system/linux.go
Labels: backport/1.2-pr

#4651 [1.2] exeseal: do not use F_SEAL_FUTURE_WRITE
  libcontainer/dmz/cloned_binary_linux.go
Labels: backport/1.2-pr

#4650 [1.2] Retry direct unix package calls if observing EINTR
  libcontainer/notify_v2_linux.go
  libcontainer/sync_unix.go
  libcontainer/utils/cmsg.go
Labels: backport/1.2-pr

#4649 [1.2] libct: don't send config to nsexec when joining an existing timens
  libcontainer/container_linux.go
  tests/integration/timens.bats
Labels: backport/1.2-pr

#4647 [1.2] libcontainer: Prevent startup hang when CloseExecFrom errors
  libcontainer/container_linux.go
Labels: backport/1.2-pr
