Repository opencontainers/runc, pull requests merged in 2025-10, with the labels that each got.

#4910 libcontainer: remove deprecated package "userns"
  CHANGELOG.md
  libcontainer/userns/userns_deprecated.go
Labels: easy-to-review, backport/1.4-todo

#4912 CHANGELOG: add v1.3.2 entry
  CHANGELOG.md
Labels: easy-to-review

#4915 [1.4] Add memory policy and schemata support
  events.go
  features.go
  go.mod
  go.sum
  internal/linux/linux.go
  libcontainer/configs/config.go
  libcontainer/configs/intelrdt.go
  libcontainer/configs/memorypolicy.go
  libcontainer/configs/tocpuset_test.go
  libcontainer/configs/validate/validator.go
  libcontainer/init_linux.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/intelrdt_test.go
  libcontainer/intelrdt/stats.go
  libcontainer/intelrdt/util_test.go
  libcontainer/setns_init_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/standard_init_linux.go
  tests/integration/memorypolicy.bats
  types/events.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/modules.txt
Labels: backport/1.4-pr

#4832 libcontainer/intelrdt: add support for EnableMonitoring field
  features.go
  libcontainer/configs/intelrdt.go
  libcontainer/configs/validate/intelrdt_test.go
  libcontainer/container_linux.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/intelrdt_test.go
  libcontainer/specconv/spec_linux.go
Labels: impact/changelog
