Repository opencontainers/runc, pull requests merged in 2025-09, with the labels that each got.

#4877 libct: user: remove deprecated module
  CHANGELOG.md
  libcontainer/user/lookup_deprecated.go
  libcontainer/user/user_deprecated.go
Labels: easy-to-review

#4892 [1.4] libcontainer/validator: allow setting user.* sysctls inside userns
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
Labels: backport/1.4-pr

#4895 [1.3] tests/int/cgroups: Use 64K aligned limits for memory.max
  tests/integration/cgroups.bats
Labels: area/ci

#4894 [1.4] tests/int/cgroups: Use 64K aligned limits for memory.max
  tests/integration/cgroups.bats
Labels: area/ci

#4812 runc exec: use CLONE_INTO_CGROUP
  libcontainer/process_linux.go
  tests/integration/exec.bats
Labels: impact/changelog
