Repository opencontainers/runc, pull requests merged in 2025-06, with the labels that each got.

#4538 Linux Network Devices
  features.go
  go.mod
  go.sum
  libcontainer/configs/config.go
  libcontainer/configs/doc.go
  libcontainer/configs/netdevices.go
  libcontainer/configs/validate/validator.go
  libcontainer/configs/validate/validator_test.go
  libcontainer/network_linux.go
  libcontainer/process_linux.go
  libcontainer/specconv/spec_linux.go
  libcontainer/specconv/spec_linux_test.go
  tests/integration/checkpoint.bats
  tests/integration/netdev.bats
  tests/integration/userns.bats
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: status/2-code-review

#4784 cgroups separation followup
  libcontainer/configs/cgroup_deprecated.go
  libcontainer/configs/config.go
Labels: backport/1.3-todo

#4788 [1.3] cgroup separation followup
  libcontainer/configs/cgroup_deprecated.go
  libcontainer/configs/config.go
Labels: backport/1.3-pr
