Repository opencontainers/runc, pull requests merged in 2025-04, with the labels that each got.

#4693 libct: we should set envs after we are in the jail of the container
  libcontainer/init_linux.go
  tests/integration/exec.bats
  tests/integration/run.bats
Labels: regression, backport/1.3-todo

#4696 criu: Add time namespace to container config after checkpoint/restore
  libcontainer/criu_linux.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, backport/1.3-todo

#4706 [1.3] libct: we should set envs after we are in the jail of the container
  libcontainer/init_linux.go
  tests/integration/exec.bats
  tests/integration/run.bats
Labels: backport/1.3-pr

#4705 [1.3] criu: Add time namespace to container config after checkpoint/restore
  libcontainer/criu_linux.go
  tests/integration/checkpoint.bats
Labels: area/checkpoint-restore, backport/1.3-pr

#4704 Override HOME if its set to the empty string
  libcontainer/env.go
  libcontainer/env_test.go
  tests/integration/env.bats
Labels: kind/bug, regression, backport/1.3-todo

#4711 [1.3] Override HOME if its set to the empty string #4704
  libcontainer/env.go
  libcontainer/env_test.go
  tests/integration/env.bats
Labels: backport/1.3-pr

#4714 [1.2] criu: Add time namespace to container config after checkpoint/restore
  libcontainer/criu_linux.go
  tests/integration/checkpoint.bats
Labels: area/ci, backport/1.2-pr

#4717 go.mod: rm toolchain
  go.mod
Labels: easy-to-review

#4709 runc pause/unpause/ps: get rid of excessive warning
  pause.go
  ps.go
  utils_linux.go
Labels: backport/1.3-todo

#4720 [1.2] runc pause/unpause/ps: get rid of excessive warning
  pause.go
  ps.go
  utils_linux.go
Labels: backport/1.2-pr

#4719 [1.3] runc pause/unpause/ps: get rid of excessive warning
  pause.go
  ps.go
  utils_linux.go
Labels: backport/1.3-pr

#4722 Completely remove --criu option
  main.go
Labels: easy-to-review, area/checkpoint-restore

#4728 ci fixes (ssh-keygen and criu version bump for almalinux 8)
  .cirrus.yml
  .github/workflows/test.yml
  script/setup_host_fedora.sh
  script/setup_rootless.sh
  tests/rootless.sh
Labels: area/ci, backport/1.2-todo, backport/1.3-todo

#4734 rootfs: improve mount-related errors
  libcontainer/mount_linux.go
  libcontainer/mount_linux_test.go
  libcontainer/rootfs_linux.go
Labels: easy-to-review, backport/1.2-todo, backport/1.3-todo

#4736 ci: update to criu-4.1-2 on Fedora
  script/setup_host_fedora.sh
Labels: area/ci, area/checkpoint-restore, backport/1.2-done, backport/1.3-done

#4742 [1.2] ci fixes (ssh-keygen and criu version bumps for almalinux 8 and fedora)
  .cirrus.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Makefile
  script/setup_host_fedora.sh
  script/setup_rootless.sh
  tests/integration/hooks.bats
  tests/integration/run.bats
  tests/integration/seccomp-notify.bats
  tests/integration/tty.bats
  tests/rootless.sh
Labels: backport/1.2-pr

#4737 [1.3] ci fixes (ssh-keygen and criu version bumps for almalinux 8 and fedora)
  .cirrus.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  Dockerfile
  Makefile
  script/setup_host_fedora.sh
  script/setup_rootless.sh
  tests/integration/hooks.bats
  tests/integration/run.bats
  tests/integration/seccomp-notify.bats
  tests/integration/tty.bats
  tests/rootless.sh
Labels: area/ci, backport/1.3-pr

#4740 [1.2] rootfs: improve mount-related errors
  libcontainer/mount_linux.go
  libcontainer/mount_linux_test.go
  libcontainer/rootfs_linux.go
Labels: backport/1.2-pr

#4738 [1.3] rootfs: improve mount-related errors
  libcontainer/mount_linux.go
  libcontainer/mount_linux_test.go
  libcontainer/rootfs_linux.go
Labels: backport/1.3-pr

#4745 [1.3][ci]: switch to golangci-lint v2
  .github/workflows/validate.yml
  .golangci-extra.yml
  .golangci.yml
  checkpoint.go
  libcontainer/capabilities/capabilities.go
  libcontainer/criu_linux.go
  libcontainer/intelrdt/cmt.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/mbm.go
  libcontainer/rootfs_linux.go
  notify_socket.go
  types/events.go
Labels: area/ci, backport/1.3-pr

#4744 [1.3] Embed version from VERSION file
  Makefile
  main.go
Labels: backport/1.3-pr

#4748 go.mod: Delete exclude directives
  go.mod
Labels: backport/1.3-done

#4749 [1.3] go.mod: Delete exclude directives
  go.mod
Labels: backport/1.3-pr

#4743 ci/cross-i386: retry adding ppa
  .github/workflows/test.yml
Labels: area/ci
