Repository opencontainers/runc, pull requests merged in 2025-07, with the labels that each got.

#4797 docs/systemd.md: amend
  docs/systemd.md
Labels: easy-to-review

#4811 [1.2] tests/int/cgroups.bats: exclude dmem controller
  tests/integration/cgroups.bats
Labels: area/ci, backport/1.2-pr

#4791 [1.2] fix rootfs propagation mode to shared / unbindable
  libcontainer/rootfs_linux.go
  tests/integration/mounts_propagation.bats
Labels: backport/1.2-pr

#4802 tests/int/events.bats: don't require root
  tests/integration/events.bats
Labels: area/ci, area/rootless

#4820 [1.2] rootfs: remove /proc/net/dev from allowed overmount list
  libcontainer/rootfs_linux.go
Labels: backport/1.2-pr
