Repository opencontainers/runc, pull requests merged in 2025-08, with the labels that each got.

#4828 runc update: don't lose intelRdt state
  update.go
Labels: kind/bug, area/intelrdt

#4834 [release-1.2] runc update: don't lose intelRdt state
  update.go
Labels: kind/bug, area/intelrdt, backport/1.2-pr

#4833 [release-1.3] runc update: don't lose intelRdt state
  update.go
Labels: kind/bug, area/intelrdt, backport/1.3-pr

#4827 runc update: refuse to create new rdt group
  update.go
Labels: area/intelrdt, backport/1.2-todo, backport/1.3-todo

#4837 script/lib.sh: remove obsoleted comment
  script/lib.sh
Labels: easy-to-review

#4765 Refactor/improve prepareCriuRestoreMounts
  libcontainer/criu_linux.go
Labels: area/checkpoint-restore

#4865 [1.3] libct: reset CPU affinity by default
  CHANGELOG.md
  libcontainer/process_linux.go
  tests/integration/cpu_affinity.bats
  tests/integration/helpers.bash
Labels: backport/1.3-pr

#4872 [1.2] Refactor/improve prepareCriuRestoreMounts
  libcontainer/criu_linux.go
Labels: area/checkpoint-restore, backport/1.2-pr

#4871 [1.3] Refactor/improve prepareCriuRestoreMounts
  libcontainer/criu_linux.go
Labels: area/checkpoint-restore, backport/1.3-pr
