Repository opencontainers/runc, pull requests merged in 2025-03, with the labels that each got.

#4654 performance improvement: setup signal notify in a new go routine
  signals.go
  utils_linux.go
Labels: kind/performance

#4660 doc: update spec-conformance.md
  docs/spec-conformance.md
Labels: area/docs, backport/1.3-todo

#4665 [1.3] doc: update spec-conformance.md
  docs/spec-conformance.md
Labels: easy-to-review, area/docs, backport/1.3-pr

#4664 CI: migrate Vagrant + Cirrus to Lima + GHA
  .cirrus.yml
  .github/workflows/test.yml
  Vagrantfile.fedora
  script/setup_host_fedora.sh
Labels: area/ci

#4667 [1.3] CI: migrate Vagrant + Cirrus to Lima + GHA
  .cirrus.yml
  .github/workflows/test.yml
  Vagrantfile.fedora
  script/setup_host_fedora.sh
Labels: backport/1.3-pr

#4671 .cirrus.yml: install less dependencies
  .cirrus.yml
Labels: area/ci, backport/1.2-todo, backport/1.3-todo

#4678 [1.2] .cirrus.yml: install less dependencies
  .cirrus.yml
Labels: area/ci, backport/1.2-pr

#4677 [1.3] .cirrus.yml: install less dependencies
  .cirrus.yml
Labels: area/ci, backport/1.3-pr

#4675 Misc CI nits
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/integration/utils_test.go
  tests/integration/selinux.bats
Labels: easy-to-review, area/ci

#4670 Shell spring cleaning
  .cirrus.yml
  .github/workflows/validate.yml
  Dockerfile
  Makefile
  script/setup_host_fedora.sh
  tests/integration/hooks.bats
  tests/integration/run.bats
  tests/integration/seccomp-notify.bats
  tests/integration/tty.bats
Labels: area/ci

#4683 [1.2] CHANGELOG: v1.2.6 formatting fixes
  CHANGELOG.md
Labels: easy-to-review

#4687 Use Go 1.23 maps.Keys, slices.Sort more
  libcontainer/capabilities/capabilities.go
  libcontainer/seccomp/config.go
Labels: easy-to-review

#4686 Remove some nolint annotations, add nolintlint linter
  .golangci.yml
  libcontainer/factory_linux_test.go
  libcontainer/integration/checkpoint_test.go
  libcontainer/integration/exec_test.go
  libcontainer/integration/execin_test.go
  libcontainer/integration/seccomp_test.go
  libcontainer/rootfs_linux.go
  libcontainer/utils/cmsg.go
Labels: area/ci, kind/refactor

#4698 ci: bump codespell to v2.4.1, fix some typos
  .github/workflows/validate.yml
  libcontainer/exeseal/cloned_binary_linux.go
  libcontainer/internal/userns/usernsfd_linux.go
  libcontainer/utils/utils_unix.go
  tests/integration/userns.bats
Labels: area/ci

#4672 tests/int/selinux: test keyring security label
  Makefile
  tests/cmd/key_label/key_label.go
  tests/integration/selinux.bats
Labels: area/ci

#4692 ci: switch to golangci-lint v2
  .github/workflows/validate.yml
  .golangci-extra.yml
  .golangci.yml
  checkpoint.go
  libcontainer/capabilities/capabilities.go
  libcontainer/criu_linux.go
  libcontainer/intelrdt/cmt.go
  libcontainer/intelrdt/intelrdt.go
  libcontainer/intelrdt/mbm.go
  libcontainer/rootfs_linux.go
  notify_socket.go
  types/events.go
Labels: area/ci
